"""
Tests for the "divbase-cli files" commands

All tests are run against the docker compose test overlay

A clean project (its bucket is auto emptied before each test) is available to any test that requires a clean slate.
"""

import csv
import os
import shutil
from io import StringIO
from pathlib import Path

import pytest
from typer.testing import CliRunner

from divbase_cli.cli_commands.file_cli import NO_FILES_SPECIFIED_MSG, NO_UPLOAD_MATCHES_MSG
from divbase_cli.cli_exceptions import DivBaseAPIError
from divbase_cli.divbase_cli import app
from divbase_lib.divbase_constants import (
    QUERY_RESULTS_FILE_PREFIX,
    S3_MULTIPART_UPLOAD_THRESHOLD,
)
from divbase_lib.s3_checksums import calculate_composite_md5_s3_etag
from tests.e2e_integration.cli_commands.conftest import assert_divbase_403_permissions_error

runner = CliRunner()

# This is the maximum number of objects S3 will allow in a single call.
# So pagination can be validated to be working for any files cmd if use more than this number of files
S3_PAGINATION_LIMIT = 1000


@pytest.fixture(autouse=True)
def start_with_clean_project(cleaned_project_bucket):
    """
    For tests that require a project with a clean bucket, this fixture will
    ensure that the CONSTANTS["CLEANED_PROJECT"]'s bucket is empty before and after running the test.
    """
    yield


@pytest.fixture(scope="module")
def large_file_for_multipart(tmp_path_factory):
    """
    Fixture that creates a large file just above the multipart upload threshold
    with random data to test multipart upload and downloads

    Returns path to the file.
    """
    one_mib = 1024 * 1024
    large_file_path = tmp_path_factory.mktemp("large_files") / "large_random_file.vcf.gz"
    file_size = S3_MULTIPART_UPLOAD_THRESHOLD + one_mib

    with open(large_file_path, "wb") as f:
        for _ in range(file_size // one_mib):
            f.write(os.urandom(one_mib))
    return large_file_path


def calculate_numb_table_rows_printed(stdout: str) -> int:
    """
    Helper to count the number of table rows printed in the stdout of a command.
    You can use this to validate how many data rows were printed in a table generated by Rich.
    """
    table_size = [line for line in stdout.splitlines() if line.strip().startswith(("│", "┃"))]
    return len(table_size) - 1  # Subtract 1 for the header


@pytest.mark.parametrize(
    "command",
    [
        "upload",
        "download",
        "rm",
        "restore",
    ],
)
def test_files_commands_fail_without_files(logged_in_edit_user_with_existing_config, CONSTANTS, command):
    """Test that different files subcommands that require file inputs fail when none are provided."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    full_command = f"files {command} --project {clean_project}"

    result = runner.invoke(app, full_command)
    assert result.exit_code == 1
    assert NO_FILES_SPECIFIED_MSG in result.stdout


def test_list_files(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test basic usage of files ls command, with and without detailed output."""
    default_project = CONSTANTS["DEFAULT_PROJECT"]

    command = "files ls"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    for file in CONSTANTS["PROJECT_CONTENTS"][default_project]:
        assert file in result.stdout

    command = "files ls --detailed"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    for file in CONSTANTS["PROJECT_CONTENTS"][default_project]:
        assert file in result.stdout

    for line in result.stdout.splitlines():
        numb_parts = line.split()
        assert len(numb_parts) == 6  # [file name] [size] [size units] [date] [time] [timezone]


def test_list_non_default_project(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test list files for the non-default project."""
    non_default_project = CONSTANTS["NON_DEFAULT_PROJECT"]
    files_in_project = CONSTANTS["PROJECT_CONTENTS"][non_default_project]

    command = f"files ls --project {non_default_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    for file in files_in_project:
        assert file in result.stdout


def test_list_files_empty_project(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test list files for an empty project."""
    command = f"files ls --project {CONSTANTS['EMPTY_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert "No files or folders found" in result.stdout


def test_list_files_hides_results_files_by_default(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that query result files are hidden by default and shown with the --include-results-files flag."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    results_file = tmp_path / f"{QUERY_RESULTS_FILE_PREFIX}1.vcf.gz"
    normal_file = tmp_path / "my_data.tsv"
    results_file.write_text("results file")
    normal_file.write_text("data file")

    upload_command = f"files upload {results_file} {normal_file} --project {clean_project}"
    upload_result = runner.invoke(app, upload_command)
    assert upload_result.exit_code == 0

    list_command = f"files ls --project {clean_project}"
    list_result = runner.invoke(app, list_command)
    assert list_result.exit_code == 0
    assert "my_data.tsv" in list_result.stdout
    assert f"{QUERY_RESULTS_FILE_PREFIX}1.vcf.gz" not in list_result.stdout

    list_command_include = f"files ls --project {clean_project} --include-results-files"
    list_result_include = runner.invoke(app, list_command_include)
    assert list_result_include.exit_code == 0
    assert "my_data.tsv" in list_result_include.stdout
    assert f"{QUERY_RESULTS_FILE_PREFIX}1.vcf.gz" in list_result_include.stdout


def test_list_files_with_prefix_filter(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that the --prefix flag correctly filters the file list."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    (tmp_path / "prefix_a_1.tsv").write_text("a1")
    (tmp_path / "prefix_a_2.tsv").write_text("a2")
    (tmp_path / "prefix_b_1.tsv").write_text("b1")

    upload_command = f"files upload {tmp_path / 'prefix_a_1.tsv'} {tmp_path / 'prefix_a_2.tsv'} {tmp_path / 'prefix_b_1.tsv'} --project {clean_project}"
    upload_result = runner.invoke(app, upload_command)
    assert upload_result.exit_code == 0

    list_command = f"files ls  prefix_a --project {clean_project}"
    list_result = runner.invoke(app, list_command)
    assert list_result.exit_code == 0
    assert "prefix_a_1.tsv" in list_result.stdout
    assert "prefix_a_2.tsv" in list_result.stdout
    assert "prefix_b_1.tsv" not in list_result.stdout


def test_list_soft_deleted_files(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """
    Test that the 'files ls --show-deleted-files' command lists soft-deleted files.
    It should also show soft deleted results files by default, so this is also checked here.
    """
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "soft_deleted_file.tsv"
    test_file.write_text("This file will be soft-deleted.")
    test_results_file = tmp_path / f"{QUERY_RESULTS_FILE_PREFIX}181291829182.vcf.gz"
    test_results_file.write_text("This is a test results file.")

    result = runner.invoke(app, f"files upload {test_file} {test_results_file} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files rm {test_file.name} {test_results_file.name} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files ls --project {clean_project} --show-deleted-files")
    assert result.exit_code == 0
    assert test_file.name in result.stdout
    assert test_results_file.name in result.stdout

    # now filter by prefix and confirm only the results file is shown
    result = runner.invoke(app, f"files ls {QUERY_RESULTS_FILE_PREFIX} --project {clean_project} --show-deleted-files")
    assert result.exit_code == 0
    assert test_file.name not in result.stdout
    assert test_results_file.name in result.stdout


def test_list_soft_deleted_files_empty_project(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test that 'files ls --show-deleted-files' shows no files in an empty project."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    result = runner.invoke(app, f"files ls --project {clean_project} --show-deleted-files")
    assert result.exit_code == 0
    assert "no soft deleted files found" in result.stdout.lower()


def test_list_soft_deleted_does_not_allow_include_results_flag(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test that 'files ls --show-deleted-files' cannot be used with --include-results-files."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    result = runner.invoke(app, f"files ls --project {clean_project} --show-deleted-files --include-results-files")
    assert result.exit_code != 0


def test_list_files_with_prefix_filtering(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that ls with a folder prefix shows only the files inside that folder."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    inside1 = tmp_path / "inside1.tsv"
    inside2 = tmp_path / "inside2.tsv"
    outside = tmp_path / "outside.tsv"
    inside1.write_text("inside 1")
    inside2.write_text("inside 2")
    outside.write_text("outside")

    result = runner.invoke(app, f"files upload {inside1} {inside2} --to vcfs/ --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files upload {outside} --project {clean_project}")
    assert result.exit_code == 0

    ls_result = runner.invoke(app, f"files ls vcfs/ --project {clean_project}")
    assert ls_result.exit_code == 0
    assert "inside1.tsv" in ls_result.stdout
    assert "inside2.tsv" in ls_result.stdout
    assert "outside.tsv" not in ls_result.stdout


def test_ls_detailed_with_folders_present(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that ls --detailed succeeds and lists folders when the project contains both files and folders."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    dir_name = "mydir/"
    file_in_dir = tmp_path / "file_in_dir.tsv"
    file_in_root = tmp_path / "file_in_root.tsv"
    file_in_dir.write_text("content")
    file_in_root.write_text("content")

    result = runner.invoke(app, f"files upload {file_in_dir} --to {dir_name} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files upload {file_in_root} --project {clean_project}")
    assert result.exit_code == 0

    # ls at root, should show the folder but not the file inside it
    result = runner.invoke(app, f"files ls --detailed --project {clean_project}")
    assert result.exit_code == 0
    assert file_in_root.name in result.stdout
    assert f"{dir_name}" in result.stdout
    assert "inside_folder.tsv" not in result.stdout

    # ls for the folder, should show the file inside it
    result = runner.invoke(app, f"files ls {dir_name} --detailed --project {clean_project}")
    assert result.exit_code == 0
    assert file_in_dir.name in result.stdout
    assert f"{dir_name}" not in result.stdout
    assert file_in_root.name not in result.stdout


def test_file_info_single_version(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files info' command for a file with a single version."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "info_test.tsv"
    test_file.write_text("some content")

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files info {test_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert f"{test_file.name}" in result.stdout
    assert calculate_numb_table_rows_printed(result.stdout) == 1


def test_file_info_deleted_file(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files info' command for a file that has been deleted."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "deleted_info_test.tsv"
    test_file.write_text("this file will be deleted")

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files rm {test_file.name} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files info {test_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert "Warning: This file is marked as soft deleted" in result.stdout


def test_file_info_multiple_versions(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test 'files info' for a file with multiple versions."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "multi_version_test.tsv"

    test_file.write_text("version 1")
    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    test_file.write_text("version 2 is different")
    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    test_file.write_text("version 3 is also different")
    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files info {test_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert "Warning: This file is marked as soft deleted" not in result.stdout
    assert calculate_numb_table_rows_printed(result.stdout) == 3


def test_file_info_on_non_existent_file_or_folder(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test 'files info' for a file that does not exist and for a folder (which should not be allowed)."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    result = runner.invoke(app, f"files info nonexistent.tsv --project {clean_project}")
    assert result.exit_code != 0
    assert isinstance(result.exception, DivBaseAPIError)
    assert "404" in str(result.exception)
    assert "does not exist" in str(result.exception)

    # that it is a folder is determined by CLI, so does not need to exist for test to work
    result = runner.invoke(app, f"files info somefolder/ --project {clean_project}")
    assert result.exit_code != 0
    assert "folder" in result.output.lower()
    assert "please provide a file" in result.output.lower()


def test_file_info_after_reupload(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test 'files info' after a file is deleted and then re-uploaded."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "reupload_test.tsv"
    test_file.write_text("initial upload")

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files rm {test_file.name} --project {clean_project}")
    assert result.exit_code == 0

    test_file.write_text("re-uploaded with new content")
    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files info {test_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert "Warning: This file is marked as soft deleted" not in result.stdout
    assert calculate_numb_table_rows_printed(result.stdout) == 2


def test_upload_1_file(logged_in_query_user_with_existing_config, tmp_path):
    """Test upload 1 file to the project."""
    test_file = tmp_path / "fake_test_file.tsv"
    test_file.write_text("testing, testing 1 2 3...")

    command = f"files upload {test_file}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert test_file.name in result.stdout


def test_upload_1_file_to_non_default_project(logged_in_query_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Specify a project when uploading a file."""
    test_file = (fixtures_dir / CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"][0]).resolve()

    command = f"files upload {test_file} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert f"{str(test_file)}" in result.stdout


def test_upload_multiple_files_at_once(logged_in_edit_user_with_existing_config, CONSTANTS, fixtures_dir):
    test_files = [(fixtures_dir / file_name).resolve() for file_name in CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"]]

    command = f"files upload {' '.join(map(str, test_files))} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    for file in test_files:
        assert f"{str(file)}" in result.stdout


def test_upload_dir_contents(logged_in_query_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Test upload all files in a directory using a glob pattern."""
    files = [x for x in fixtures_dir.glob("*") if x.is_file()]  # does not get subdirs

    command = f"files upload {fixtures_dir.resolve()}/* --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    clean_stdout = result.stdout.replace("\n", "")  # newlines can cause issues in the assert below
    for file in files:
        assert str(file.resolve()) in clean_stdout


@pytest.mark.parametrize(
    "glob_pattern_template, expected_file_names",
    [
        # All .vcf.gz files in a flat directory
        ("{data_dir}/*.vcf.gz", ["a.vcf.gz", "b.vcf.gz"]),
        # All .tsv files in current directory
        ("{data_dir}/*.tsv", ["meta.tsv", "another_metadata.tsv", "one_more.tsv"]),
        # Nested:
        ("{data_dir}/*/sub/*.vcf.gz", ["nested.vcf.gz"]),
    ],
)
def test_upload_glob_patterns(
    logged_in_query_user_with_existing_config, CONSTANTS, tmp_path, glob_pattern_template, expected_file_names
):
    """Test that glob patterns are correctly expanded when specifying files to upload."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    # Create the temp directory structure expected by each pattern
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / "a.vcf.gz").write_bytes(b"vcf content a")
    (data_dir / "b.vcf.gz").write_bytes(b"vcf content b")
    (data_dir / "meta.tsv").write_text("col1\tcol2\n")
    (data_dir / "another_metadata.tsv").write_text("col1\tcol2\n")
    (data_dir / "one_more.tsv").write_text("col1\tcol2\n")
    nested_dir = data_dir / "group" / "sub"
    nested_dir.mkdir(parents=True)
    (nested_dir / "nested.vcf.gz").write_bytes(b"nested vcf content")

    glob_pattern = glob_pattern_template.format(data_dir=data_dir)
    command = f"files upload '{glob_pattern}' --project {clean_project}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0, result.output
    for file_name in expected_file_names:
        assert file_name in result.stdout


def test_upload_recursive_flag_matches_subdirectories(logged_in_query_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that --recursive expands ** patterns into subdirectories."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / "top.tsv").write_text("top level")
    sub_dir = data_dir / "sub"
    sub_dir.mkdir()
    (sub_dir / "deep.tsv").write_text("nested")

    command = f"files upload --recursive '{data_dir}/**' --project {clean_project}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0, result.output
    assert "top.tsv" in result.stdout
    assert "deep.tsv" in result.stdout


def test_upload_without_recursive_does_not_match_subdirectories(
    logged_in_query_user_with_existing_config, CONSTANTS, tmp_path
):
    """Test that without --recursive, ** patterns do not descend into subdirectories."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    data_dir = tmp_path / "data"
    data_dir.mkdir()
    sub_dir = data_dir / "sub"
    sub_dir.mkdir()
    (sub_dir / "only_nested.tsv").write_text("nested only")

    command = f"files upload '{data_dir}/**' --project {clean_project}"
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert NO_UPLOAD_MATCHES_MSG in result.stdout


def test_upload_duplicate_file_names_rejected(logged_in_query_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that uploading two files with the same name from different directories raises an error."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    dir_a = tmp_path / "a"
    dir_b = tmp_path / "b"
    dir_a.mkdir()
    dir_b.mkdir()
    (dir_a / "data.tsv").write_text("version a")
    (dir_b / "data.tsv").write_text("version b")

    command = f"files upload {dir_a / 'data.tsv'} {dir_b / 'data.tsv'} --project {clean_project}"
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert "appear more than once" in result.stdout.lower()
    assert "data.tsv" in result.stdout


def test_upload_recursive_preserves_subdir_paths(logged_in_query_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that --recursive upload with same-named files in different subdirs succeeds because they get distinct keys."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    data_dir = tmp_path / "data"
    (data_dir / "group_a").mkdir(parents=True)
    (data_dir / "group_b").mkdir(parents=True)
    (data_dir / "group_a" / "samples.tsv").write_text("group a samples")
    (data_dir / "group_b" / "samples.tsv").write_text("group b samples")

    command = f"files upload --recursive '{data_dir}/**' --project {clean_project}"
    result = runner.invoke(app, command)

    # Same filename in different subdirs is NOT a duplicate — keys are group_a/samples.tsv and group_b/samples.tsv
    assert result.exit_code == 0
    assert "group_a/samples.tsv" in result.stdout
    assert "group_b/samples.tsv" in result.stdout


def test_upload_skip_existing_skips_already_uploaded_files(
    logged_in_query_user_with_existing_config, CONSTANTS, tmp_path
):
    """Test that --skip-existing skips files already in the project and uploads only new ones."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    existing_file = tmp_path / "existing.tsv"
    new_file = tmp_path / "new.tsv"
    existing_file.write_text("already uploaded content")
    new_file.write_text("new content")

    # Upload the existing file first
    result = runner.invoke(app, f"files upload {existing_file} --project {clean_project}")
    assert result.exit_code == 0

    # should fail as no --skip-existing flag
    result = runner.invoke(app, f"files upload {existing_file} {new_file}  --project {clean_project}")
    assert result.exit_code != 0
    assert "--skip-existing" in result.stdout

    # with --skip-existing flag, new should be uploaded, old should be skipped
    command = f"files upload --skip-existing {existing_file} {new_file} --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0, result.output
    assert "skipped" in result.stdout.lower()
    assert "existing.tsv" in result.stdout
    assert "new.tsv" in result.stdout
    assert "successfully uploaded" in result.stdout.lower()

    # now run again with --skip-existing, should skip both as they are now both uploaded, but not fail
    command = f"files upload --skip-existing {existing_file} {new_file} --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0, result.output
    assert "skipped" in result.stdout.lower()
    assert "existing.tsv" in result.stdout
    assert "new.tsv" in result.stdout
    assert "no files were uploaded" in result.stdout.lower()


def test_upload_dry_run_shows_files_without_uploading(logged_in_query_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that --dry-run shows which files would be uploaded but does not actually upload them."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    file1 = tmp_path / "dry1.tsv"
    file2 = tmp_path / "dry2.tsv"
    file1.write_text("dry run content 1")
    file2.write_text("dry run content 2")

    result = runner.invoke(app, f"files upload --dry-run {file1} {file2} --project {clean_project}")

    assert result.exit_code == 0, result.output
    assert "dry1.tsv" in result.stdout
    assert "dry2.tsv" in result.stdout

    # Confirm nothing was actually uploaded
    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert ls_result.exit_code == 0
    assert "dry1.tsv" not in ls_result.stdout
    assert "dry2.tsv" not in ls_result.stdout


def test_upload_dry_run_with_skip_existing_shows_skipped_and_new(
    logged_in_query_user_with_existing_config, CONSTANTS, tmp_path
):
    """Test that --dry-run --skip-existing shows which files would be skipped vs uploaded."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    existing = tmp_path / "already_there_dry.tsv"
    new_file = tmp_path / "new_dry.tsv"
    existing.write_text("already uploaded content")
    new_file.write_text("brand new content")

    result = runner.invoke(app, f"files upload {existing} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(
        app, f"files upload --dry-run --skip-existing {existing} {new_file} --project {clean_project}"
    )

    assert result.exit_code == 0, result.output
    assert "already_there_dry.tsv" in result.stdout
    assert "new_dry.tsv" in result.stdout
    assert "skipped" in result.stdout.lower()
    assert "would have been uploaded" in result.stdout.lower()

    # Confirm new file was not actually uploaded
    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert "new_dry.tsv" not in ls_result.stdout


def test_reupload_same_file_fails(logged_in_query_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Test upload with safe mode on (default) works the first time, but fails on subsequent attempts."""
    file_name = CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"][0]
    file_path = f"{fixtures_dir}/{file_name}"
    command = f"files upload {file_path} --project {CONSTANTS['CLEANED_PROJECT']}"

    result = runner.invoke(app, command)
    assert result.exit_code == 0

    result = runner.invoke(app, command)
    assert result.exit_code != 0
    assert "the exact version of the following files" in result.stdout.lower()
    assert "already exist" in result.stdout.lower()


def test_reupload_of_same_file_with_safe_mode_off_works(
    logged_in_query_user_with_existing_config, CONSTANTS, fixtures_dir
):
    """Test upload with safe mode off works for reuploading the same file."""
    file_name = CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"][0]
    file_path = f"{fixtures_dir}/{file_name}"
    command = f"files upload {file_path} --project {CONSTANTS['CLEANED_PROJECT']} --disable-safe-mode"

    result = runner.invoke(app, command)
    assert result.exit_code == 0

    result = runner.invoke(app, command)
    assert result.exit_code == 0


def test_no_file_uploaded_if_some_duplicated(logged_in_query_user_with_existing_config, CONSTANTS, fixtures_dir):
    """
    Test that no files are uploaded with safe mode on (which is the default)
    if at least 1 of the files trying to be uploaded already exists in the project's bucket.
    """
    test_files = [(fixtures_dir / file_name).resolve() for file_name in CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"]]

    # upload just 1 of the files first
    command = f"files upload {test_files[0]} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    # none should be uploaded as the first one already exists
    command = f"files upload {' '.join(map(str, test_files))} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code != 0
    assert "the exact version of the following files" in result.stdout.lower()
    assert "already exist" in result.stdout.lower()

    command = f"files ls --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert test_files[0].name in result.stdout
    for file in test_files[1:]:
        assert file.name not in result.stdout, f"File {file.name} was uploaded when it shouldn't have been."


def test_upload_nonexistent_files(logged_in_query_user_with_existing_config, tmp_path):
    """
    Test that uploading nonexistent files fails with helpful error msg about which files do not exist
    """
    real_file = tmp_path / "new.tsv"
    real_file.write_text("I exist! :)")
    real_file_str = str(real_file.resolve())

    command = "files upload nonexistent_file.tsv"
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert NO_UPLOAD_MATCHES_MSG in result.stdout
    assert "nonexistent_file.tsv" in result.stdout

    # only those that don't exist should be in the error message.
    command = f"files upload nonexistent_file.tsv another_nonexistent_file.vcf.gz {real_file_str}"
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert NO_UPLOAD_MATCHES_MSG in result.stdout
    assert "nonexistent_file.tsv" in result.stdout
    assert "another_nonexistent_file.vcf.gz" in result.stdout
    assert real_file_str not in result.stdout

    # same idea as above but using globs
    real_file_glob = real_file_str[:-4] + "*"
    command = f"files upload 'nonexistent*' 'another*.vcf.gz' {real_file_glob}"
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert NO_UPLOAD_MATCHES_MSG in result.stdout
    assert "nonexistent*" in result.stdout
    assert "another*.vcf.gz" in result.stdout
    assert real_file_glob not in result.stdout


@pytest.mark.parametrize(
    "file_names, expected_error",
    [
        (["data.tsv", "variants.vcf.gz", "index.csi", "index.tbi", "README.md", "supported.txt"], None),
        (["unsupported.rst"], "file_type"),
        (["archive.zip"], "file_type"),
        (["data.tsv", "variants.mine.vcf.gz"], None),
        (["data.tsv", "supported.txt", "unsupported1.vcf", "unsupported2.gzip"], "file_type"),
        (["variants.vcf.gz", "variants2.vcf.gz", "index.tbi", "index.csi"], None),
        (["unsupported.rst", "another_unsupported.zip", "supported.vcf.gz"], "file_type"),
        (["dat:a.tsv"], "file_chars"),
        (["variants2.vcf.gz", "invalid:file.tsv"], "file_chars"),
    ],
)
def test_upload_non_supported_files(
    logged_in_query_user_with_existing_config, CONSTANTS, tmp_path, file_names, expected_error
):
    """
    Tests that the upload command correctly handles
    supported and unsupported file types and file names with not supported characters.
    """
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_files = []
    for file_name in file_names:
        test_file = tmp_path / file_name
        test_file.write_text("file content")
        test_files.append(str(test_file))

    command = f"files upload {' '.join(test_files)} --project {clean_project}"
    result = runner.invoke(app, command)

    if expected_error is None:
        assert result.exit_code == 0
        assert "successfully uploaded" in result.stdout.lower()
    elif expected_error == "file_type":
        assert result.exit_code != 0
        assert "types are not supported" in result.stdout.lower()
    elif expected_error == "file_chars":
        assert result.exit_code != 0
        assert "unsupported characters" in result.stdout.lower()


def test_safe_mode_fails_with_large_file_duplicate(
    logged_in_edit_user_with_existing_config, CONSTANTS, large_file_for_multipart
):
    """
    Tests that safe mode correctly identifies a duplicate large file (which has a composite ETag)
    and prevents the re-upload.

    Turning off safe mode should allow the re-upload.
    """
    large_file_path = large_file_for_multipart

    command = f"files upload {large_file_path} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    result = runner.invoke(app, command)
    assert result.exit_code != 0
    assert "the exact version of the following files" in result.stdout.lower()
    assert "already exist" in result.stdout.lower()
    assert large_file_path.name in result.stdout

    # validate turning off safe mode allows re-upload
    command = f"files upload {large_file_path} --project {CONSTANTS['CLEANED_PROJECT']} --disable-safe-mode"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert large_file_path.name in result.stdout


def test_download_1_file(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    file_name = CONSTANTS["PROJECT_CONTENTS"][CONSTANTS["DEFAULT_PROJECT"]][0]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    command = f"files download {file_name} --download-dir {download_dir}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert file_name in result.stdout
    assert (download_dir / file_name).exists()


def test_download_multiple_files(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    files_in_project = CONSTANTS["PROJECT_CONTENTS"][CONSTANTS["DEFAULT_PROJECT"]]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    command = f"files download {' '.join(files_in_project)} --download-dir {download_dir}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    for file_name in files_in_project:
        assert file_name in result.stdout
        assert (download_dir / file_name).exists()


def test_download_from_non_default_project(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    non_default_project = CONSTANTS["NON_DEFAULT_PROJECT"]
    file_to_download = CONSTANTS["PROJECT_CONTENTS"][non_default_project][0]

    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    command = f"files download {file_to_download} --project {non_default_project} --download-dir {download_dir}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert file_to_download in result.stdout
    assert (download_dir / file_to_download).exists()


def test_download_using_file_list(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    files_in_project = CONSTANTS["PROJECT_CONTENTS"][CONSTANTS["DEFAULT_PROJECT"]]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_list = tmp_path / "file_list.tsv"
    with open(file_list, "w") as f:
        f.write("\n".join(files_in_project))

    command = f"files download --file-list {file_list} --download-dir {download_dir}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    for file_name in files_in_project:
        assert file_name in result.stdout
        assert (download_dir / file_name).exists()


def test_download_mix_of_files_and_folders(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Folder prefix and explicit files can be downloaded in one command."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_0_deep = tmp_path / "file_0_deep.tsv"
    file_1_deep = tmp_path / "level_1" / "level_1_file.tsv"
    file_2_deep = tmp_path / "level_1" / "level_2" / "level_2_file.tsv"
    file_2_deep.parent.mkdir(parents=True, exist_ok=True)

    file_0_deep.write_text("0")
    file_1_deep.write_text("1")
    file_2_deep.write_text("2")

    # upload the files to the project bucket, preserve the directory structure by using the recursive flag and a glob pattern
    result = runner.invoke(app, f"files upload '{tmp_path}/**/*.tsv' --project {clean_project} --recursive")
    assert result.exit_code == 0

    # download all files via specifying the root file and the level_1 folder
    download_cmd = f"files download {file_0_deep.name} level_1/ --download-dir {download_dir} --project {clean_project}"
    result = runner.invoke(app, download_cmd)
    assert result.exit_code == 0, result.stdout
    assert (download_dir / file_0_deep.name).exists()
    assert (download_dir / "level_1" / file_1_deep.name).exists()
    assert (download_dir / "level_1" / "level_2" / file_2_deep.name).exists()

    # when run with flatten the files should now all end up in the same directory
    result = runner.invoke(app, download_cmd + " --flatten")
    assert result.exit_code == 0, result.stdout
    assert (download_dir / file_1_deep.name).exists()
    assert (download_dir / file_2_deep.name).exists()


def test_download_nonexistent_file_and_folder(logged_in_edit_user_with_existing_config, tmp_path):
    """Test that downloading a nonexistent file or contents of nonexistent folder fails with a helpful error message."""
    non_existent_file = "nonexistent_file.tsv"
    non_existent_folder = "nonexistent_folder/"
    command = f"files download {non_existent_file} "
    result = runner.invoke(app, command)

    assert result.exit_code != 0
    assert "failed to download the following files:" in result.stdout.lower()
    assert non_existent_file in result.stdout

    result = runner.invoke(app, f"files download {non_existent_folder}")
    assert result.exit_code != 0
    assert "no files found" in result.stdout.lower()
    assert non_existent_folder in result.stdout


def test_download_specific_file_versions(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """
    Tests that the download command can fetch a specific older version of one file
    and the latest version of another file in the same command.
    """
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "download_version_test"
    download_dir.mkdir()

    versioned_file = tmp_path / "versioned_file.tsv"
    versioned_file.write_text("content v1")
    result = runner.invoke(app, f"files upload {versioned_file} --project {clean_project}")
    assert result.exit_code == 0

    versioned_file.write_text("content latest v2")
    result = runner.invoke(app, f"files upload {versioned_file} --project {clean_project}")
    assert result.exit_code == 0

    latest_file = tmp_path / "latest_file.tsv"
    latest_file.write_text("content latest v1")
    result = runner.invoke(app, f"files upload {latest_file} --project {clean_project}")
    assert result.exit_code == 0

    latest_file.write_text("content latest v2")
    result = runner.invoke(app, f"files upload {latest_file} --project {clean_project}")
    assert result.exit_code == 0

    # Get the version ID for versioned_file
    info_command = f"files info {versioned_file.name} --project {clean_project} --tsv"
    info_result = runner.invoke(app, info_command)
    assert info_result.exit_code == 0
    tsv_reader = csv.reader(StringIO(info_result.stdout), delimiter="\t")
    rows = list(tsv_reader)
    # The first data row is the latest version (v2), the second is the older one (v1)
    version_id_v1 = rows[2][3]

    download_command = (
        f"files download {versioned_file.name}:{version_id_v1} {latest_file.name} "
        f"--project {clean_project} --download-dir {download_dir}"
    )
    download_result = runner.invoke(app, download_command)
    assert download_result.exit_code == 0
    assert "Successfully downloaded" in download_result.stdout

    downloaded_versioned_file = download_dir / versioned_file.name
    assert downloaded_versioned_file.exists()
    assert downloaded_versioned_file.read_text() == "content v1"

    downloaded_latest_file = download_dir / latest_file.name
    assert downloaded_latest_file.exists()
    assert downloaded_latest_file.read_text() == "content latest v2"


def test_download_at_a_project_version(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path, fixtures_dir):
    """Test downloading at specified project versions."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    download_dir = tmp_path / "download_v1"
    download_dir.mkdir()

    file_name = "test_file.tsv"
    file_path = tmp_path / file_name
    v1_content = "This is version 1.0.0 content"
    v2_content = "This is version 2.0.0 content - UPDATED"

    # Create file, upload v1 contents and create project version v1.0.0
    with open(file_path, "w") as f:
        f.write(v1_content)

    command = f"files upload {file_path} --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    command = f"version add v1.0.0 --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    # Create file, upload v2 contents and create project version v2.0.0
    with open(file_path, "w") as f:
        f.write(v2_content)

    command = f"files upload {file_path} --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    command = f"version add v2.0.0 --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    # Download + assert contents at v1.0.0
    command = (
        f"files download {file_name} --project-version v1.0.0 --project {clean_project} --download-dir {download_dir}"
    )
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert (download_dir / file_name).exists()

    with open(download_dir / file_name) as f:
        downloaded_content = f.read()
    assert downloaded_content == v1_content

    # Download + assert contents at v2.0.0
    command = (
        f"files download {file_name} --project-version v2.0.0 --project {clean_project} --download-dir {download_dir}"
    )
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert (download_dir / file_name).exists()

    with open(download_dir / file_name) as f:
        downloaded_content = f.read()
    assert downloaded_content == v2_content

    # Download without specifying project version works like "latest"
    command = f"files download {file_name} --project {clean_project} --download-dir {download_dir}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert (download_dir / file_name).exists()

    with open(download_dir / file_name) as f:
        downloaded_content = f.read()
    assert downloaded_content == v2_content


def test_upload_and_download_large_file_triggers_multipart(
    logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path, large_file_for_multipart
):
    """
    Tests that a file large enough to trigger the multipart protocol can be successfully
    uploaded and then downloaded, verifying its checksum.
    """
    large_file_path = large_file_for_multipart
    expected_checksum = calculate_composite_md5_s3_etag(file_path=large_file_path)

    command = f"files upload {large_file_path} --project {CONSTANTS['CLEANED_PROJECT']}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert large_file_path.name in result.stdout

    download_dir = tmp_path / "large_file_downloads"
    download_dir.mkdir()
    command = (
        f"files download {large_file_path.name} --project {CONSTANTS['CLEANED_PROJECT']} --download-dir {download_dir}"
    )
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    # manually verify checksum of downloaded file (should have also been verified during download)
    downloaded_file_path = download_dir / large_file_path.name
    assert downloaded_file_path.exists()
    downloaded_checksum = calculate_composite_md5_s3_etag(file_path=downloaded_file_path)
    assert downloaded_checksum == expected_checksum


def test_download_all_cmd(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files download-all' command."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    test_files = {
        "file1.tsv": "content 1",
        "file2.tsv": "content 2",
        "file3.vcf.gz": "fake vcf content",
    }
    for name, content in test_files.items():
        (tmp_path / name).write_text(content)
        result = runner.invoke(app, f"files upload {tmp_path / name} --project {clean_project}")
        assert result.exit_code == 0

    command = f"files download-all --project {clean_project} --download-dir {download_dir}"
    result = runner.invoke(app, command, input="y\n")

    assert result.exit_code == 0
    assert "There are '3' files to download" in result.stdout
    assert "Successfully downloaded" in result.stdout
    for name, content in test_files.items():
        assert name in result.stdout
        downloaded_file = download_dir / name
        assert downloaded_file.exists()
        assert downloaded_file.read_text() == content


def test_download_all_dry_run(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files download-all --dry-run' command."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_name = "dry_run_test.tsv"
    (tmp_path / file_name).write_text("dry run content")
    result = runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project}")
    assert result.exit_code == 0

    command = f"files download-all --project {clean_project} --download-dir {download_dir} --dry-run"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert "dry run" in result.stdout.lower()
    assert file_name in result.stdout
    assert not (download_dir / file_name).exists()


def test_download_all_resume_skip(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files download-all --resume' command where files already exist and match checksum."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_name = "resume_skip_test.tsv"
    content = "matching content"
    (tmp_path / file_name).write_text(content)
    result = runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project}")
    assert result.exit_code == 0

    # First download
    runner.invoke(app, f"files download-all --project {clean_project} --download-dir {download_dir}", input="y\n")
    assert (download_dir / file_name).exists()

    # Second download with --resume
    command = f"files download-all --project {clean_project} --download-dir {download_dir} --resume"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert "No files left to download" in result.stdout
    assert "your folder matches the project's store" in result.stdout


def test_download_all_resume_overwrite(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test the 'files download-all --resume' command where files already exist but have different checksum."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_name = "resume_overwrite_test.tsv"
    original_content = "original server content"
    (tmp_path / file_name).write_text(original_content)
    result = runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project}")
    assert result.exit_code == 0

    (download_dir / file_name).write_text("different local content")

    # download-all --resume, should warn, we cancel the run this time, as warning should come before prompt
    command = f"files download-all --project {clean_project} --download-dir {download_dir} --resume"
    result = runner.invoke(app, command, input="n\n")
    assert result.exit_code == 0
    assert "Warning: The following files already exist" in result.stdout
    assert file_name in result.stdout

    # now run it for real and validate actually overwrote.
    result = runner.invoke(app, command, input="y\n")
    assert (download_dir / file_name).read_text() == original_content


def test_download_all_at_project_version(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test 'files download-all --project-version' command."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_name = "version_test.tsv"
    v1_content = "v1 content"
    v2_content = "v2 content"
    project_version = "download_at_project_version_test"

    # upload v1, create project version, upload v2
    (tmp_path / file_name).write_text(v1_content)
    runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project}")
    runner.invoke(app, f"version add {project_version} --project {clean_project}")
    (tmp_path / file_name).write_text(v2_content)
    runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project} --disable-safe-mode")

    command = f"files download-all --project {clean_project} --download-dir {download_dir} --project-version {project_version}"
    result = runner.invoke(app, command, input="y\n")

    assert result.exit_code == 0
    assert (download_dir / file_name).read_text() == v1_content


def test_download_all_empty_project(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test 'files download-all' for an empty project."""
    empty_project = CONSTANTS["EMPTY_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    command = f"files download-all --project {empty_project} --download-dir {download_dir}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert "no files to download" in result.stdout.lower()


def test_download_all_user_aborts(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test 'files download-all' when user says 'no' to confirmation."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "downloads"
    download_dir.mkdir()

    file_name = "abort_test.tsv"
    (tmp_path / file_name).write_text("some content")
    runner.invoke(app, f"files upload {tmp_path / file_name} --project {clean_project}")

    command = f"files download-all --project {clean_project} --download-dir {download_dir}"
    result = runner.invoke(app, command, input="n\n")
    assert result.exit_code == 0
    assert not (download_dir / file_name).exists()


def test_download_all_flatten(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that download-all --flatten places all files directly in the download dir, ignoring subfolders."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    download_dir = tmp_path / "flat_dl"
    download_dir.mkdir()

    root_file = tmp_path / "root_flat.tsv"
    nested_file = tmp_path / "nested_flat.tsv"
    root_file.write_text("at root")
    nested_file.write_text("nested content")

    runner.invoke(app, f"files upload {root_file} --project {clean_project}")
    runner.invoke(app, f"files upload {nested_file} --to subdir/ --project {clean_project}")

    command = f"files download-all --flatten --project {clean_project} --download-dir {download_dir}"
    result = runner.invoke(app, command, input="y\n")

    assert result.exit_code == 0, result.output
    assert (download_dir / "root_flat.tsv").exists()
    assert (download_dir / "nested_flat.tsv").exists()
    assert not (download_dir / "subdir").exists()


def test_download_and_download_all_with_flatten_collision_rejected(
    logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path
):
    """Test that both download and download-all with --flatten errors when the project contains files that share same filename"""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    shared_name = tmp_path / "data.tsv"
    shared_name.write_text("content")

    result = runner.invoke(app, f"files upload {shared_name} --to vcfs/ --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files upload {shared_name} --to samples/ --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files download vcfs/data.tsv samples/data.tsv --flatten --project {clean_project}")
    assert result.exit_code != 0
    assert "--flatten" in result.stdout
    assert "would overwrite each other" in result.stdout.lower()

    result = runner.invoke(app, f"files download-all --flatten --project {clean_project}")
    assert result.exit_code != 0
    assert "--flatten" in result.stdout
    assert "would overwrite each other" in result.stdout.lower()


def test_stream_file(logged_in_edit_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Test streaming a simple text file."""
    query_project = CONSTANTS["QUERY_PROJECT"]
    file_to_stream = "sample_metadata.tsv"
    file_path = fixtures_dir / file_to_stream
    expected_content = file_path.read_text()

    result = runner.invoke(app, f"files stream {file_to_stream} --project {query_project}")
    assert result.exit_code == 0
    assert result.stdout == expected_content


def test_stream_gzipped_file(logged_in_edit_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Test streaming a gzipped file."""
    query_project = CONSTANTS["QUERY_PROJECT"]
    file_to_stream = "HOM_20ind_17SNPs_first_10_samples.vcf.gz"
    file_path = fixtures_dir / file_to_stream
    expected_content = file_path.read_bytes()

    result = runner.invoke(app, f"files stream {file_to_stream} --project {query_project}")
    assert result.exit_code == 0
    assert result.stdout_bytes == expected_content


def test_remove_with_dry_run(logged_in_edit_user_with_existing_config, CONSTANTS):
    file_name = CONSTANTS["PROJECT_CONTENTS"][CONSTANTS["DEFAULT_PROJECT"]][0]

    command = f"files rm {file_name} --dry-run"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert f"{file_name}" in result.stdout

    command = "files ls"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert file_name in result.stdout


def test_remove_file(logged_in_edit_user_with_existing_config, CONSTANTS, fixtures_dir):
    """Test removing a file from the project's bucket, using a clean project to avoid side effects in other tests."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    file_name = CONSTANTS["FILES_TO_UPLOAD_DOWNLOAD"][0]
    file_path = f"{fixtures_dir}/{file_name}"

    command = f"files upload {file_path} --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0

    command = f"files ls --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert file_name in result.stdout

    command = f"files rm {file_name} --project {clean_project}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    assert f"{file_name}" in result.stdout

    command = f"files ls --project {clean_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    assert file_name not in result.stdout


def test_restore_deleted_file(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test restoring a file that was soft-deleted."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "file_to_restore.tsv"
    test_file.write_text("This file will be deleted and then restored.")

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files rm {test_file.name} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files download {test_file.name} --project {clean_project} --download-dir {tmp_path}")
    assert result.exit_code != 0
    assert "404" in result.stdout
    assert test_file.name in result.stdout

    result = runner.invoke(app, f"files restore {test_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert "restored files:" in result.stdout.lower()
    assert test_file.name in result.stdout

    result = runner.invoke(app, f"files download {test_file.name} --project {clean_project} --download-dir {tmp_path}")
    assert result.exit_code == 0
    assert "404" not in result.stdout
    assert test_file.name in result.stdout
    assert "successfully downloaded" in result.stdout.lower()


def test_restore_already_live_file(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that attempting to restore a multiple times does no harm and operation is idempotent."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    test_file = tmp_path / "already_alive_file.tsv"
    test_file.write_text("This file was never deleted.")

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0

    for _ in range(3):
        result = runner.invoke(app, f"files restore {test_file.name} --project {clean_project}")
        assert result.exit_code == 0
        assert "restored files:" in result.stdout.lower()
        assert test_file.name in result.stdout

    result = runner.invoke(app, f"files download {test_file.name} --project {clean_project} --download-dir {tmp_path}")
    assert result.exit_code == 0
    assert "404" not in result.stdout
    assert test_file.name in result.stdout
    assert "successfully downloaded" in result.stdout.lower()


def test_upload_remove_restore_using_file_list(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test uploading, removing, and restoring soft-deleted files using --file-list option."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    file1 = tmp_path / "a.tsv"
    file2 = tmp_path / "b.tsv"
    file1.write_text("a")
    file2.write_text("b")

    # needs full path for upload, but just the name for rm/restore
    upload_list = tmp_path / "file_list.txt"
    upload_list.write_text(f"{file1}\n{file2}")
    rm_restore_list = tmp_path / "rm_restore_list.txt"
    rm_restore_list.write_text(f"{file1.name}\n{file2.name}")

    result = runner.invoke(app, f"files upload --file-list {upload_list} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files rm --file-list {rm_restore_list} --project {clean_project}")
    assert result.exit_code == 0

    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert result.exit_code == 0
    assert "a.tsv" not in ls_result.stdout
    assert "b.tsv" not in ls_result.stdout

    result = runner.invoke(app, f"files restore --file-list {rm_restore_list} --project {clean_project}")
    assert result.exit_code == 0
    assert "a.tsv" in result.stdout
    assert "b.tsv" in result.stdout

    # Confirm files are live again
    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert result.exit_code == 0
    assert "a.tsv" in ls_result.stdout
    assert "b.tsv" in ls_result.stdout


def test_restore_non_existent_file(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test that attempting to restore a non-existent file reports it as 'not found'."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    non_existent_file = "i_do_not_exist.tsv"

    result = runner.invoke(app, f"files restore {non_existent_file} --project {clean_project}")
    assert result.exit_code != 0
    assert "warning: some files could not be restored" in result.stdout.lower()
    assert non_existent_file in result.stdout


def test_restore_file_with_exact_key_match_among_similar_prefixes(
    logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path
):
    """
    Test that the 'files restore' command restores the correct file when there are multiple files in the bucket
    with similar prefixes. Verifies that only the file with the exact key match is restored, and that the other files
    with matching prefix is not affected.

    This test is because of how s3 lets you list objects with a prefix (but not do exact match listing),
    which can lead to multiple files being returned if they share a common prefix.
    """
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    prefix_matching_file = tmp_path / "i_am_a_file.tsv"
    exact_file = tmp_path / "i_am_a_file.txt.vcf.gz"
    prefix_matching_file.write_text("This file will be deleted and NOT restored.")
    exact_file.write_text("This file will be deleted and then restored.")

    result = runner.invoke(app, f"files upload {prefix_matching_file} {exact_file} --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files rm {prefix_matching_file.name} {exact_file.name} --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files restore {exact_file.name} --project {clean_project}")
    assert result.exit_code == 0
    assert "restored files:" in result.stdout.lower()
    assert exact_file.name in result.stdout

    # Confirm by attempting to download each file
    result = runner.invoke(app, f"files download {exact_file.name} --project {clean_project} --download-dir {tmp_path}")
    assert result.exit_code == 0
    assert "successfully downloaded" in result.stdout.lower()
    result = runner.invoke(
        app, f"files download {prefix_matching_file.name} --project {clean_project} --download-dir {tmp_path}"
    )
    assert result.exit_code != 0
    assert "404" in result.stdout


def test_mkdir_command(logged_in_query_user_with_existing_config, CONSTANTS):
    """Test basic mkdir functionality and that it can be run multiple times in a row."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    folders = ["vcfs", "samples", "metadata"]
    result = runner.invoke(app, f"files mkdir {' '.join(folders)} --project {clean_project}")
    assert result.exit_code == 0
    assert "successfully created" in result.stdout.lower()

    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert ls_result.exit_code == 0
    for folder in folders:
        assert folder in ls_result.stdout

    # (cmd is idempotent)
    result = runner.invoke(app, f"files mkdir {' '.join(folders)} --project {clean_project}")
    assert result.exit_code == 0
    assert "successfully created" in result.stdout.lower()


def test_mkdir_normalizes_directory_names(logged_in_query_user_with_existing_config, CONSTANTS):
    """Test that mkdir adds a trailing slash if missing, and strips a leading slash."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    # "vcfs" becomes "vcfs/"
    result = runner.invoke(app, f"files mkdir vcfs --project {clean_project}")
    assert result.exit_code == 0
    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert "vcfs/" in ls_result.stdout

    # "/data/" becomes creates "data/"
    result = runner.invoke(app, f"files mkdir /data/ --project {clean_project}")
    assert result.exit_code == 0
    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert "data/" in ls_result.stdout
    assert "/data/" not in ls_result.stdout


def test_mkdir_unsupported_characters_rejected(logged_in_query_user_with_existing_config, CONSTANTS):
    """Test that mkdir rejects directory names containing unsupported characters."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    result = runner.invoke(app, f"files mkdir 'invalid:dir' --project {clean_project}")
    assert result.exit_code != 0
    assert "unsupported characters" in result.stdout.lower()


def test_rmdir_removes_empty_directory(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test that rmdir removes an empty directory and it no longer appears in ls."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    result = runner.invoke(app, f"files mkdir vcfs --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files rmdir vcfs --project {clean_project}")
    assert result.exit_code == 0
    assert "deleted" in result.stdout.lower()

    ls_result = runner.invoke(app, f"files ls --project {clean_project}")
    assert ls_result.exit_code == 0
    assert "vcfs" not in ls_result.stdout


def test_rmdir_fails_on_non_empty_directory(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that rmdir fails when the directory still contains files."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    test_file = tmp_path / "data.tsv"
    test_file.write_text("some content")
    result = runner.invoke(app, f"files upload {test_file} --to data/ --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files rmdir data --project {clean_project}")
    assert result.exit_code != 0
    assert "not empty" in result.stdout.lower()


def test_rmdir_nonexistent_directory_succeeds(logged_in_edit_user_with_existing_config, CONSTANTS):
    """Test that rmdir on a non-existent directory exits successfully (idempotent)."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    result = runner.invoke(app, f"files rmdir i_do_not_exist --project {clean_project}")
    assert result.exit_code == 0


def test_files_tree_cmd(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that 'files tree' command can handle folders and dirs and do prefix filtering"""
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    root_file = tmp_path / "root.tsv"
    root_file.write_text("root")
    nested_file = tmp_path / "nested.tsv"
    nested_file.write_text("nested")
    very_nested_file = tmp_path / "very_nested.tsv"
    very_nested_file.write_text("very nested")

    result = runner.invoke(app, f"files upload {root_file} --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(app, f"files upload {nested_file} --to vcfs/ --project {clean_project}")
    assert result.exit_code == 0
    result = runner.invoke(
        app, f"files upload {very_nested_file} --to vcfs/subdir/subsubdir/ --project {clean_project}"
    )
    assert result.exit_code == 0

    result = runner.invoke(app, f"files mkdir empty_dir --project {clean_project}")
    assert result.exit_code == 0

    result = runner.invoke(app, f"files tree --project {clean_project}")
    assert result.exit_code == 0
    assert "vcfs" in result.stdout
    assert "subdir" in result.stdout
    assert "subsubdir" in result.stdout
    assert "empty_dir" in result.stdout
    assert "root.tsv" in result.stdout
    assert "nested.tsv" in result.stdout
    assert "very_nested.tsv" in result.stdout

    # prefix to just vcfs/ and check that only those files/folders are shown
    result = runner.invoke(app, f"files tree vcfs/ --project {clean_project}")
    assert result.exit_code == 0
    assert "vcfs" in result.stdout
    assert "subdir" in result.stdout
    assert "subsubdir" in result.stdout
    assert "nested.tsv" in result.stdout
    assert "very_nested.tsv" in result.stdout

    assert "empty_dir" not in result.stdout
    assert "root.tsv" not in result.stdout


def test_tree_hides_results_files_by_default(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Test that 'files tree' hides DivBase query results files by default."""
    clean_project = CONSTANTS["CLEANED_PROJECT"]
    results_file = tmp_path / f"{QUERY_RESULTS_FILE_PREFIX}1.vcf.gz"
    normal_file = tmp_path / "data.tsv"
    results_file.write_text("results")
    normal_file.write_text("data")

    runner.invoke(app, f"files upload {results_file} {normal_file} --project {clean_project}")

    result = runner.invoke(app, f"files tree --project {clean_project}")
    assert result.exit_code == 0
    assert "data.tsv" in result.stdout
    assert results_file.name not in result.stdout

    result = runner.invoke(app, f"files tree --include-results-files --project {clean_project}")
    assert result.exit_code == 0
    assert results_file.name in result.stdout


### Permissions tests for different files commands.
def test_read_user_file_permissions(logged_in_read_user_with_existing_config, CONSTANTS, tmp_path):
    """Read role cannot upload or delete files or make dirs."""
    test_file = tmp_path / "test.tsv"
    test_file.write_text("col1\tcol2\nval1\tval2")

    result = runner.invoke(app, f"files upload {test_file} --project {CONSTANTS['CLEANED_PROJECT']}")
    assert_divbase_403_permissions_error(result)

    result = runner.invoke(app, f"files rm {test_file.name} --project {CONSTANTS['CLEANED_PROJECT']}")
    assert_divbase_403_permissions_error(result)

    result = runner.invoke(app, f"files mkdir vcfs --project {CONSTANTS['CLEANED_PROJECT']}")
    assert_divbase_403_permissions_error(result)


def test_query_user_file_permissions(logged_in_query_user_with_existing_config, CONSTANTS, tmp_path):
    """Query role can upload files and create dirs but cannot delete files or dirs."""
    test_file = tmp_path / "test.tsv"
    test_file.write_text("col1\tcol2\nval1\tval2")

    result = runner.invoke(app, f"files upload {test_file} --project {CONSTANTS['CLEANED_PROJECT']}")
    assert result.exit_code == 0
    assert "successfully uploaded" in result.stdout.lower()

    result = runner.invoke(app, f"files mkdir test_dir --project {CONSTANTS['CLEANED_PROJECT']}")
    assert result.exit_code == 0
    assert "successfully created" in result.stdout.lower()

    result = runner.invoke(app, f"files rm {test_file.name} --project {CONSTANTS['CLEANED_PROJECT']}")
    assert_divbase_403_permissions_error(result)

    result = runner.invoke(app, f"files rmdir test_dir --project {CONSTANTS['CLEANED_PROJECT']}")
    assert_divbase_403_permissions_error(result)


def test_edit_user_file_permissions(logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path):
    """Edit role can upload and delete files."""
    test_file = tmp_path / "test_edit_perms.tsv"
    test_file.write_text("col1\tcol2\nval1\tval2")
    clean_project = CONSTANTS["CLEANED_PROJECT"]

    result = runner.invoke(app, f"files upload {test_file} --project {clean_project}")
    assert result.exit_code == 0
    assert "successfully uploaded" in result.stdout.lower()

    result = runner.invoke(app, f"files rm {test_file.name} --project {clean_project}")
    assert result.exit_code == 0


#### Slow tests designed to test pagination/batching logic in all relevant files cli commands. ####
# These will only be run when you do pytest --run-slow


@pytest.fixture(scope="function")
def pagination_files_uploaded(
    logged_in_edit_user_with_existing_config, CONSTANTS, tmp_path_factory, request
) -> tuple[list[str], list[Path]]:
    """
    Fixture that creates and uploads large numbers of files to PAGINATION_PROJECT bucket.
    (So we don't have to do it separately in each test)
    Returns the list of file names uploaded and their paths.

    This fixture counts as the test for pagination working for uploads.
    """
    if not request.config.getoption("--run-slow"):
        pytest.skip("Only run when --run-slow is given")

    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    num_files = S3_PAGINATION_LIMIT + 5
    upload_dir = tmp_path_factory.mktemp("pagination_files")

    file_names = [f"pagination_test_{i}.tsv" for i in range(num_files)]
    file_paths = []
    for name in file_names:
        file_path = upload_dir / name
        file_paths.append(file_path)
        file_path.write_text(f"content_{name}")

    # Check if files are already uploaded to avoid re-running
    list_command = f"files ls --project {pagination_project} --tsv"
    list_result = runner.invoke(app, list_command)
    assert list_result.exit_code == 0
    already_uploaded = all(name in list_result.stdout for name in file_names)

    if not already_uploaded:
        upload_command = f"files upload '{upload_dir}/*' --project {pagination_project} --skip-existing"
        upload_result = runner.invoke(app, upload_command)
        assert upload_result.exit_code == 0

    return file_names, file_paths


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_list_files_handles_pagination(logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded):
    """
    Tests that the list files command can paginate correctly by going through all results when a project
    contains more than s3 limit for a single API call.
    """
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, _ = pagination_files_uploaded

    list_command = f"files ls --project {pagination_project}"
    list_result = runner.invoke(app, list_command)
    assert list_result.exit_code == 0

    for name in file_names:
        assert name in list_result.stdout


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_list_soft_deleted_files_handles_pagination(
    logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded
):
    """Test that the 'files ls --show-deleted-files' command handles pagination correctly."""
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, _ = pagination_files_uploaded

    # Delete all files to make them soft-deleted
    delete_command = f"files rm {' '.join(file_names)} --project {pagination_project}"
    delete_result = runner.invoke(app, delete_command)
    assert delete_result.exit_code == 0

    list_command = f"files ls --project {pagination_project} --show-deleted-files"
    list_result = runner.invoke(app, list_command)
    assert list_result.exit_code == 0

    for name in file_names:
        assert name in list_result.stdout

    # Restore them for other tests
    restore_command = f"files restore {' '.join(file_names)} --project {pagination_project}"
    result = runner.invoke(app, restore_command)
    assert result.exit_code == 0
    for name in file_names:
        assert name in result.stdout


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_download_handles_pagination(
    logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded, tmp_path
):
    """
    Tests that the batching logic for 'files download' works correctly when downloading
    more than S3_PAGINATION_LIMIT files at once.
    """
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, _ = pagination_files_uploaded
    download_dir = tmp_path / "downloads_dir"
    download_dir.mkdir()

    command = f"files download {' '.join(file_names)} --download-dir {download_dir} --project {pagination_project}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    for name in file_names:
        assert name in result.stdout
        assert (download_dir / name).exists()


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_download_all_handles_pagination(
    logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded, tmp_path
):
    """Tests that 'files download-all' correctly handles pagination"""
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, _ = pagination_files_uploaded
    download_dir = tmp_path / "downloads_dir"
    download_dir.mkdir()

    command = f"files download-all --project {pagination_project} --download-dir {download_dir}"
    result = runner.invoke(app, command, input="y\n")

    assert result.exit_code == 0
    assert f"there are '{len(file_names)}' files to download" in result.stdout.lower()
    for name in file_names:
        assert name in result.stdout
        assert (download_dir / name).exists()


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_upload_safe_mode_fails_with_pagination_if_one_exists(
    logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded, tmp_path
):
    """
    Tests that safe mode correctly identifies a duplicate file and raises an error to prevent upload,
    even when the check involves more than S3_PAGINATION_LIMIT files.

    The duplicated file would not be in the 1st batch of files to be uploaded as well, but should prevent any file being uploaded.

    NOTE: files upload "happy path" with pagination is convered by the fixture, so don't need a separate test.
    """
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, files_in_bucket = pagination_files_uploaded

    upload_dir = tmp_path / "uploads_dir"
    upload_dir.mkdir()
    num_files = S3_PAGINATION_LIMIT + 5
    safe_mode_files = [f"safe_mode_test_{i}.tsv" for i in range(num_files - 1)]

    for idx, file_name in enumerate(safe_mode_files):
        (upload_dir / file_name).write_text(f"content_{idx}")

    # Add the duplicate file (already in bucket) to upload dir
    duplicate_file = files_in_bucket[S3_PAGINATION_LIMIT + 1]
    shutil.copy(src=duplicate_file, dst=upload_dir)

    command = f"files upload '{upload_dir}/*' --project {pagination_project}"
    result = runner.invoke(app, command)
    assert result.exit_code != 0
    assert "the exact version of the following files" in result.stdout.lower()
    assert "already exist" in result.stdout.lower()
    assert duplicate_file.name in result.stdout

    # Verify that none of the files were uploaded.
    command = f"files ls --project {pagination_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    for file_name in safe_mode_files:
        assert file_name not in result.stdout

    # Now run the upload again without safe_mode, should work
    command = f"files upload '{upload_dir}/*' --project {pagination_project} --disable-safe-mode"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    for file_name in safe_mode_files:
        assert file_name in result.stdout

    # delete them so as to not mess with other tests
    command = f"files rm {' '.join(safe_mode_files)} --project {pagination_project}"
    result = runner.invoke(app, command)
    assert result.exit_code == 0
    for name in safe_mode_files:
        assert name in result.stdout


@pytest.mark.skipif("not config.getoption('--run-slow')", reason="Only run when --run-slow is given")
def test_remove_and_restore_files_handles_pagination(
    logged_in_edit_user_with_existing_config, CONSTANTS, pagination_files_uploaded
):
    """
    Tests that 'files rm' and 'files restore' correctly handles a large number of files by batching the requests.
    By restoring we make sure all files are back again for the other tests.
    """
    pagination_project = CONSTANTS["PAGINATION_PROJECT"]
    file_names, _ = pagination_files_uploaded

    command = f"files rm {' '.join(file_names)} --project {pagination_project}"
    result = runner.invoke(app, command)

    assert result.exit_code == 0
    for name in file_names:
        assert name in result.stdout

    list_result = runner.invoke(app, f"files ls --project {pagination_project}")
    assert "no files or folders found" in list_result.stdout.lower()

    restore_command = f"files restore {' '.join(file_names)} --project {pagination_project}"
    result = runner.invoke(app, restore_command)

    assert result.exit_code == 0
    assert "restored files" in result.stdout.lower()
    for name in file_names:
        assert name in result.stdout

    list_result = runner.invoke(app, f"files ls --project {pagination_project}")
    for name in file_names:
        assert name in list_result.stdout
