"""initial_migration

Revision ID: c7060f86aa37
Revises:
Create Date: 2025-12-03 10:53:35.032982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7060f86aa37"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("bucket_name", sa.String(length=63), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("storage_quota_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_bucket_name"), "project", ["bucket_name"], unique=True)
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=False)
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("date_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_password_change", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.create_table(
        "project_membership",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("READ", "EDIT", "MANAGE", name="projectroles"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_id", name="unique_user_project"),
    )
    op.create_index(op.f("ix_project_membership_id"), "project_membership", ["id"], unique=False)
    op.create_index(op.f("ix_project_membership_project_id"), "project_membership", ["project_id"], unique=False)
    op.create_index(op.f("ix_project_membership_role"), "project_membership", ["role"], unique=False)
    op.create_index(op.f("ix_project_membership_user_id"), "project_membership", ["user_id"], unique=False)
    op.create_table(
        "revoked_token",
        sa.Column("token_jti", sa.String(length=36), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("ACCESS", "REFRESH", "EMAIL_VERIFICATION", "PASSWORD_RESET", name="tokentype"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "revoked_reason", sa.Enum("LOGOUT", "TOKEN_USED", "MANUAL_REVOKE", name="tokenrevokereason"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revoked_token_id"), "revoked_token", ["id"], unique=False)
    op.create_index(op.f("ix_revoked_token_token_jti"), "revoked_token", ["token_jti"], unique=True)
    op.create_index(op.f("ix_revoked_token_token_type"), "revoked_token", ["token_type"], unique=False)
    op.create_index(op.f("ix_revoked_token_user_id"), "revoked_token", ["user_id"], unique=False)
    op.create_table(
        "skipped_vcf_files",
        sa.Column("vcf_file_s3_key", sa.String(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("s3_version_id", sa.String(), nullable=False),
        sa.Column("skip_reason", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vcf_file_s3_key", "project_id", name="unique_skipped_vcf_per_project"),
    )
    op.create_index(op.f("ix_skipped_vcf_files_id"), "skipped_vcf_files", ["id"], unique=False)
    op.create_index(op.f("ix_skipped_vcf_files_project_id"), "skipped_vcf_files", ["project_id"], unique=False)
    op.create_index(op.f("ix_skipped_vcf_files_s3_version_id"), "skipped_vcf_files", ["s3_version_id"], unique=False)
    op.create_index(
        op.f("ix_skipped_vcf_files_vcf_file_s3_key"), "skipped_vcf_files", ["vcf_file_s3_key"], unique=False
    )
    op.create_table(
        "task_history",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "STARTED", "SUCCESS", "FAILURE", "RETRY", "REVOKED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("result_message", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "id"),
    )
    op.create_index(op.f("ix_task_history_id"), "task_history", ["id"], unique=False)
    op.create_index(op.f("ix_task_history_project_id"), "task_history", ["project_id"], unique=False)
    op.create_index(op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_history_user_id"), "task_history", ["user_id"], unique=False)
    op.create_table(
        "vcf_metadata",
        sa.Column("vcf_file_s3_key", sa.String(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("s3_version_id", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("samples", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("scaffolds", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("variant_count", sa.BigInteger(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vcf_file_s3_key", "project_id", name="unique_vcf_per_project"),
    )
    op.create_index(op.f("ix_vcf_metadata_id"), "vcf_metadata", ["id"], unique=False)
    op.create_index(op.f("ix_vcf_metadata_project_id"), "vcf_metadata", ["project_id"], unique=False)
    op.create_index(op.f("ix_vcf_metadata_s3_version_id"), "vcf_metadata", ["s3_version_id"], unique=False)
    op.create_index(op.f("ix_vcf_metadata_samples"), "vcf_metadata", ["samples"], unique=False)
    op.create_index(op.f("ix_vcf_metadata_vcf_file_s3_key"), "vcf_metadata", ["vcf_file_s3_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vcf_metadata_vcf_file_s3_key"), table_name="vcf_metadata")
    op.drop_index(op.f("ix_vcf_metadata_samples"), table_name="vcf_metadata")
    op.drop_index(op.f("ix_vcf_metadata_s3_version_id"), table_name="vcf_metadata")
    op.drop_index(op.f("ix_vcf_metadata_project_id"), table_name="vcf_metadata")
    op.drop_index(op.f("ix_vcf_metadata_id"), table_name="vcf_metadata")
    op.drop_table("vcf_metadata")
    op.drop_index(op.f("ix_task_history_user_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_project_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_id"), table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_skipped_vcf_files_vcf_file_s3_key"), table_name="skipped_vcf_files")
    op.drop_index(op.f("ix_skipped_vcf_files_s3_version_id"), table_name="skipped_vcf_files")
    op.drop_index(op.f("ix_skipped_vcf_files_project_id"), table_name="skipped_vcf_files")
    op.drop_index(op.f("ix_skipped_vcf_files_id"), table_name="skipped_vcf_files")
    op.drop_table("skipped_vcf_files")
    op.drop_index(op.f("ix_revoked_token_user_id"), table_name="revoked_token")
    op.drop_index(op.f("ix_revoked_token_token_type"), table_name="revoked_token")
    op.drop_index(op.f("ix_revoked_token_token_jti"), table_name="revoked_token")
    op.drop_index(op.f("ix_revoked_token_id"), table_name="revoked_token")
    op.drop_table("revoked_token")
    op.drop_index(op.f("ix_project_membership_user_id"), table_name="project_membership")
    op.drop_index(op.f("ix_project_membership_role"), table_name="project_membership")
    op.drop_index(op.f("ix_project_membership_project_id"), table_name="project_membership")
    op.drop_index(op.f("ix_project_membership_id"), table_name="project_membership")
    op.drop_table("project_membership")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_index(op.f("ix_project_bucket_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
