"""add_project_versioning_table

Revision ID: 5b559e3008f4
Revises: 86ef3d9ea91b
Create Date: 2025-12-18 11:29:46.047191

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b559e3008f4"
down_revision: Union[str, Sequence[str], None] = "86ef3d9ea91b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_version",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("date_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "project_id", name="unique_name_project"),
    )
    op.create_index(op.f("ix_project_version_id"), "project_version", ["id"], unique=False)
    op.create_index(op.f("ix_project_version_name"), "project_version", ["name"], unique=False)
    op.create_index(op.f("ix_project_version_project_id"), "project_version", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_version_project_id"), table_name="project_version")
    op.drop_index(op.f("ix_project_version_name"), table_name="project_version")
    op.drop_index(op.f("ix_project_version_id"), table_name="project_version")
    op.drop_table("project_version")
    # ### end Alembic commands ###
