"""postgres_for_tasks

Revision ID: 26d87d16239d
Revises: c5a18386f0b6
Create Date: 2025-12-10 12:16:42.876825

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d87d16239d"
down_revision: Union[str, Sequence[str], None] = "c5a18386f0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_history", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("task_history", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.alter_column("task_history", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("task_history", "project_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.create_index(op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.create_index(op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=False)
    op.alter_column("task_history", "project_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("task_history", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("task_history", "completed_at")
    op.drop_column("task_history", "started_at")
    # ### end Alembic commands ###
