"""add_queue_status_db_model

Revision ID: 755a240de0ab
Revises: 03964a15e9ed
Create Date: 2026-03-19 11:57:16.792455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "755a240de0ab"
down_revision: Union[str, Sequence[str], None] = "03964a15e9ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: The 'id' is set to autoincrement, which is not actually needed
    # This is because we are inheriting it from basedb model and it does no harm to have autoincrement=true.
    op.create_table(
        "queue_status",
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_for_users", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id = 1", name="queue_status_singleton_row"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_queue_status_id"), "queue_status", ["id"], unique=False)
    # ### end Alembic commands ###
    ### human added - create the initial singleton row
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO queue_status (id, is_closed, reason_for_users) VALUES (1, false, 'The queuing system is currently closed for new tasks due to planned upcoming maintenance. Please try again later.')"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queue_status_id"), table_name="queue_status")
    op.drop_table("queue_status")
    # ### end Alembic commands ###
