"""add_pat_table

Revision ID: 18530b8a3e93
Revises: 755a240de0ab
Create Date: 2026-04-09 08:52:58.432434

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "18530b8a3e93"
down_revision: Union[str, Sequence[str], None] = "755a240de0ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_access_token",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("hashed_token", sa.String(length=64), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("date_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_access_token_hashed_token"), "personal_access_token", ["hashed_token"], unique=True
    )
    op.create_index(op.f("ix_personal_access_token_id"), "personal_access_token", ["id"], unique=False)
    op.create_index(op.f("ix_personal_access_token_user_id"), "personal_access_token", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_personal_access_token_user_id"), table_name="personal_access_token")
    op.drop_index(op.f("ix_personal_access_token_id"), table_name="personal_access_token")
    op.drop_index(op.f("ix_personal_access_token_hashed_token"), table_name="personal_access_token")
    op.drop_table("personal_access_token")
    # ### end Alembic commands ###
