"""add_date_deleted_to_projectdb

Revision ID: 3881392cf212
Revises: 9885301b9073
Create Date: 2026-07-14 07:08:31.889867

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3881392cf212"
down_revision: Union[str, Sequence[str], None] = "9885301b9073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("date_deleted", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "date_deleted")
    # ### end Alembic commands ###
