"""add annoucements db

Revision ID: 2ec979fc9dbb
Revises: 3e168ddc857e
Create Date: 2026-02-09 09:43:52.822149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ec979fc9dbb"
down_revision: Union[str, Sequence[str], None] = "3e168ddc857e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcement",
        sa.Column("heading", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=True),
        sa.Column("target", sa.Enum("BOTH", "CLI", "WEB", name="announcementtarget"), nullable=False),
        sa.Column("level", sa.Enum("INFO", "SUCCESS", "WARNING", "DANGER", name="announcementlevel"), nullable=False),
        sa.Column("auto_expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_announcement_heading"), "announcement", ["heading"], unique=False)
    op.create_index(op.f("ix_announcement_id"), "announcement", ["id"], unique=False)
    op.create_index(op.f("ix_announcement_level"), "announcement", ["level"], unique=False)
    op.create_index(op.f("ix_announcement_target"), "announcement", ["target"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcement_target"), table_name="announcement")
    op.drop_index(op.f("ix_announcement_level"), table_name="announcement")
    op.drop_index(op.f("ix_announcement_id"), table_name="announcement")
    op.drop_index(op.f("ix_announcement_heading"), table_name="announcement")
    op.drop_table("announcement")
    # ### end Alembic commands ###

    # Human added, explicitly drop enums
    # see https://github.com/sqlalchemy/alembic/issues/886
    op.execute("DROP TYPE IF EXISTS announcementtarget")
    op.execute("DROP TYPE IF EXISTS announcementlevel")
