"""add_organisation_to_user_model

Revision ID: faa3d0318fda
Revises: 2ec979fc9dbb
Create Date: 2026-02-10 12:09:49.979031

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faa3d0318fda"
down_revision: Union[str, Sequence[str], None] = "2ec979fc9dbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # adjusted to set default value to the literal text Not specified to prevent issues with existing users,
    # as the column is not nullable
    op.add_column(
        "user",
        sa.Column(
            "organisation",
            sa.String(length=200),
            nullable=False,
            server_default=sa.text("'Not specified'"),
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "organisation_role",
            sa.String(length=100),
            nullable=False,
            server_default=sa.text("'Not specified'"),
        ),
    )
    # ### end Alembic commands ###
    # human added commands to remove server default after setting default value for existing records
    op.alter_column("user", "organisation", server_default=None)
    op.alter_column("user", "organisation_role", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "organisation_role")
    op.drop_column("user", "organisation")
    # ### end Alembic commands ###
