"""add_task_name_to_task_history

Revision ID: 2bacb6c69c9e
Revises: 3881392cf212
Create Date: 2026-10-08 14:49:21.114350

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bacb6c69c9e"
down_revision: Union[str, Sequence[str], None] = "3881392cf212"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server default sets the literal text 'unknown' for existing task history entries, as the column is not nullable
    op.add_column(
        "task_history",
        sa.Column("task_name", sa.String(), nullable=False, server_default=sa.text("'unknown'")),
    )
    # remove server default after setting the value for existing records
    op.alter_column("task_history", "task_name", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_history", "task_name")
    # ### end Alembic commands ###
