"""task_name_to_task_history

Revision ID: 1d9d677c1eee
Revises: 03964a15e9ed
Create Date: 2026-03-13 12:25:26.163071

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d9d677c1eee"
down_revision: Union[str, Sequence[str], None] = "03964a15e9ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_history", sa.Column("task_name", sa.String(), nullable=True))
    op.create_index(op.f("ix_task_history_task_name"), "task_history", ["task_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_history_task_name"), table_name="task_history")
    op.drop_column("task_history", "task_name")
    # ### end Alembic commands ###
