"""mod_jsonb_contents_in_project_versions

Revision ID: 03964a15e9ed
Revises: bde261f949a1
Create Date: 2026-03-09 08:57:32.044213

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03964a15e9ed"
down_revision: Union[str, Sequence[str], None] = "bde261f949a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # We are changing the structure of the JSONB column,
    # so easiest to clear out all existing entries to avoid issues with the new structure.
    # As this project is in development, okay to do this at this time point.
    # New structure is:
    # {
    #   "file_name1": {"version_id": "v1", "etag": "etag1", "size": 1024},
    #   "file_name2": {"version_id": "v2", "etag": "etag2", "size": 2048}
    # }
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM project_version"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # As above, as JSONB structure changes between these migrations, need to drop the entries to avoid issues.
    # Old structure was:
    # {
    #   "file_name1": "version_id1",
    #   "file_name2": "version_id2"
    # }
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM project_version"))
