services:
  tools:
    image: "bcftools-image"
    volumes:
      - ..:/app
    build:
      context: .
      dockerfile: tools.dockerfile
  rabbitmq:
    image: "rabbitmq:alpine"
    ports:
    - 5672:5672
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  worker:
    build:
      context: .. 
      dockerfile: docker/worker.dockerfile
    depends_on:
      - rabbitmq
      - tools
      - redis
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ../src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: mher/flower:0.9.7
    ports:
      - 5555:5555
    depends_on:
      - redis
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=5555
    command: ["flower", "--broker=pyamqp://guest@rabbitmq:5672//", "--persistent=True"]
volumes:
  redis-data: