name: divbase-job-system
services:
  rabbitmq:
    image: "rabbitmq:alpine"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5672:5672
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  worker:
    build:
      context: .. 
      dockerfile: docker/worker.dockerfile
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ../src:/app/src
      - ..:/app
  flower:
    build:
      context: ..
      dockerfile: docker/flower.dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "floweradmin:badpassword", "http://localhost:5555/"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5555:5555
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=floweradmin:badpassword
    command: [
      "flower", 
      "--persistent=True",
      "--db=/data/flower.db",
      ]
    volumes:
      - flower-data:/data
volumes:
  redis-data:
  flower-data: