auth:
  rootUser: admin
  rootPassword: squirrel123

persistence:
  size: 100Mi
  storageClass: "local-path"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

service:
  type: ClusterIP
