{
 "title": "Celery Worker Prometheus Client Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (%) per Worker Process (Container/Pod; % of a Single CPU Core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_cpu_percent",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  },
  {
   "title": "CPU Time (Total Seconds) per Worker Process (Container/Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_cpu_time_total",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes) per Worker Process (Container/Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_memory_bytes",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  },
  {
   "title": "Memory Usage (%) per Worker Process (Container/Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_memory_percent",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  },
  {
   "title": "Number of Threads per Worker Process (Container/Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_num_threads",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  },
  {
   "title": "Open File Descriptors per Worker Process (Container/Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "celery_worker_prom_client_open_fds",
     "legendFormat": "{{instance}} ({{worker_name}})"
    }
   ]
  }
 ]
}