{
 "title": "RabbitMQ Overview",
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Published (per 1 minute interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_published_total{queue=~\"celery|long|quick\"}[1m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Current Queue Depth: celery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"celery\"}",
     "legendFormat": "celery"
    }
   ]
  },
  {
   "title": "Current Queue Depth: quick",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"quick\"}",
     "legendFormat": "quick"
    }
   ]
  },
  {
   "title": "Current Queue Depth: long",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"long\"}",
     "legendFormat": "long"
    }
   ]
  },
  {
   "title": "Current number of consumers per Queue: celery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"celery\"}",
     "legendFormat": "celery"
    }
   ]
  },
  {
   "title": "Current number of consumers per Queue: quick",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"quick\"}",
     "legendFormat": "quick"
    }
   ]
  },
  {
   "title": "Current number of consumers per Queue: long",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=\"long\"}",
     "legendFormat": "long"
    }
   ]
  }
 ]
}