"""
Auto generate documentation for DivBase's documentation site:

Generates:
- Docs on each divbase-cli command
- llms.txt, llms-users.txt and llms-full.txt for LLMs.
- Lists (up to 30) latest GitHub releases using the GitHub API.

The auto-generated markdown files are .gitignore'd and are generated by running
this script prior to building the documentation site (so they are always up to date).

Usage (in local development):

uv sync (if not already run)
uv run scripts/build_docs.py && uv run zensical serve
"""

import subprocess
from dataclasses import dataclass
from pathlib import Path

import httpx
import tomllib

CLI_SAVE_DIR = Path("docs/cli/_auto_generated")
CLI_ENTRY_POINT = Path("packages/divbase-cli/src/divbase_cli/divbase_cli.py")
CLI_COMMANDS_SRC_DIR = Path("packages/divbase-cli/src/divbase_cli/cli_commands")

RELEASES_DIR = Path("docs/releases")
RELEASES_PAGE = RELEASES_DIR / "index.md"
GITHUB_REPO = "ScilifelabDataCentre/divbase"
DIVBASE_RELEASES_URL = f"https://github.com/{GITHUB_REPO}/releases"

BASE_DIVBASE_URL = "https://divbase.scilifelab-2-prod.sys.kth.se"
BASE_DOCS_URL = "https://scilifelabdatacentre.github.io/divbase"
DOCS_DIR = Path("docs")
ZENSICAL_TOML = Path("zensical.toml")
LLMS_TXT_FILE = DOCS_DIR / "llms.txt"
LLMS_FULL_FILE = DOCS_DIR / "llms-full.txt"
LLMS_USERS_FILE = DOCS_DIR / "llms-users.txt"
# Sections included in llms-users.txt (i.e. no Dev Guide or Releases)
LLMS_USERS_SECTIONS = ["DivBase", "User Guides", "CLI Commands"]

SUB_COMMANDS = {
    "auth": CLI_COMMANDS_SRC_DIR / "auth_cli.py",
    "config": CLI_COMMANDS_SRC_DIR / "user_config_cli.py",
    "dimensions": CLI_COMMANDS_SRC_DIR / "dimensions_cli.py",
    "files": CLI_COMMANDS_SRC_DIR / "file_cli.py",
    "query": CLI_COMMANDS_SRC_DIR / "query_cli.py",
    "task-history": CLI_COMMANDS_SRC_DIR / "task_history_cli.py",
    "version": CLI_COMMANDS_SRC_DIR / "version_cli.py",
}

_LLMS_TXT_HEADER = f"""\
# DivBase

> A service to manage, query and version VCF files and associated sample metadata.

DivBase is a platform for centralized storage, collaborative sharing, and queryable access to genomic VCF variant files and associated sample metadata.
Users interact with DivBase via `divbase-cli` (CLI) or the web interface at {BASE_DIVBASE_URL}.
Queries combine bcftools-based VCF filtering with sidecar TSV sample metadata filtering.
"""


@dataclass(frozen=True)
class NavEntry:
    """A single entry in the zensical.toml nav section."""

    section: str
    title: str
    doc_path: str

    @property
    def html_url(self) -> str:
        """The URL of the rendered HTML page on the docs site."""
        if self.doc_path.endswith("index.md"):
            html_path = self.doc_path.removesuffix("index.md")
        else:
            html_path = self.doc_path.removesuffix(".md") + "/"
        return f"{BASE_DOCS_URL}/{html_path}"


def _walk_nav(nav_items: list, top_section: str = "") -> list[NavEntry]:
    """
    Recursively walk the zensical.toml's "nav" section, returning a list of NavEntry objects.
    External URLs are skipped.
    """
    results = []
    for item in nav_items:
        if not isinstance(item, dict):
            continue
        for title, value in item.items():
            section = top_section or title
            if isinstance(value, str):
                if value.startswith("http"):
                    continue
                results.append(NavEntry(section=section, title=title, doc_path=value))
            elif isinstance(value, list):
                results.extend(_walk_nav(value, top_section=section))
    return results


def parse_all_nav_sections() -> dict[str, list[NavEntry]]:
    """Get all docs pages listed in the zensical.toml, grouped by top level section."""
    with open(ZENSICAL_TOML, "rb") as f:
        config = tomllib.load(f)
    nav_items = config["project"]["nav"]

    results: dict[str, list[NavEntry]] = {}
    for entry in _walk_nav(nav_items):
        if not (DOCS_DIR / entry.doc_path).exists():
            raise FileNotFoundError(f"{DOCS_DIR / entry.doc_path} is listed in {ZENSICAL_TOML} nav but does not exist")
        results.setdefault(entry.section, []).append(entry)
    return results


def generate_llms_txt(nav_sections: dict[str, list[NavEntry]]) -> None:
    """Generate docs/llms.txt per the llms.txt spec (https://llmstxt.org)."""
    lines = [
        _LLMS_TXT_HEADER,
        f"- [llms-users.txt]({BASE_DOCS_URL}/llms-users.txt): User guides and CLI reference concatenated in a single file (~200 KB)",
        f"- [llms-full.txt]({BASE_DOCS_URL}/llms-full.txt): Complete documentation, including the developer guide, concatenated in a single file (~400 KB)",
        "",
    ]
    for section, entries in nav_sections.items():
        lines.append(f"## {section}\n")
        for entry in entries:
            lines.append(f"- [{entry.title}]({entry.html_url})")
        lines.append("")

    LLMS_TXT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Docs saved to: {LLMS_TXT_FILE}")


def _write_concatenated_docs(
    output_file: Path, nav_sections: dict[str, list[NavEntry]], include_sections: list[str] | None = None
) -> None:
    """Concatenate nav pages in order into output_file. If include_sections is given, only include pages from those top level sections."""
    parts = []
    for section, entries in nav_sections.items():
        if include_sections is not None and section not in include_sections:
            continue
        for entry in entries:
            content = (DOCS_DIR / entry.doc_path).read_text(encoding="utf-8")
            # Drop front matter section (e.g. "search: exclude: true" on dev pages)
            if content.startswith("---\n"):
                content = content.split("---\n", 2)[2]
            parts.append(f"<!-- Source: {entry.html_url} -->\n\n{content.strip()}")

    output_file.write_text("\n\n".join(parts), encoding="utf-8")
    print(f"Docs saved to: {output_file}")


def generate_llms_full(nav_sections: dict[str, list[NavEntry]]) -> None:
    """Generate docs/llms-full.txt by concatenating all nav pages in order."""
    _write_concatenated_docs(LLMS_FULL_FILE, nav_sections)


def generate_llms_users(nav_sections: dict[str, list[NavEntry]]) -> None:
    """Generate docs/llms-users.txt, the user facing subset of llms-full.txt (no dev pages)."""
    missing_sections = [section for section in LLMS_USERS_SECTIONS if section not in nav_sections]
    if missing_sections:
        raise ValueError(
            f"LLMS_USERS_SECTIONS contains sections not found in the {ZENSICAL_TOML} nav: {missing_sections}. "
            "Was a section renamed?"
        )
    _write_concatenated_docs(LLMS_USERS_FILE, nav_sections, include_sections=LLMS_USERS_SECTIONS)


def _fetch_releases() -> list[dict]:
    """Fetch all divbase releases from GitHub API."""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/releases"
    resp = httpx.get(url, headers={"Accept": "application/vnd.github+json"}, timeout=10)
    resp.raise_for_status()
    return resp.json()


# pagination rules of API mean up to 100 per request with default of up to 30, I think that is enough for this mirror.
# aka no need to loop through pages here...
_RELEASES_INTRO = f"""---
search:
  exclude: true
---

# DivBase Releases

Releases are managed on GitHub — the content below is a replica containing up to the 30 latest pulled from the [GitHub releases page]({DIVBASE_RELEASES_URL}) at build time.

"""

_RELEASES_FALLBACK = f"""---
search:
  exclude: true
---

# DivBase Releases

Releases are managed on GitHub — see the
[GitHub releases page]({DIVBASE_RELEASES_URL}) for the full list.
"""


def generate_releases_page() -> None:
    """Generate docs/releases/index.md from GitHub releases."""
    RELEASES_DIR.mkdir(parents=False, exist_ok=True)
    try:
        releases = _fetch_releases()
    except httpx.HTTPError as exc:
        print(f"WARNING: Could not fetch GitHub releases ({exc}). Writing fallback page.")
        RELEASES_PAGE.write_text(_RELEASES_FALLBACK)
        return

    lines = [_RELEASES_INTRO]
    for release in releases:
        if release.get("draft"):
            continue
        name = release["name"]
        date = release["published_at"][:10]  # YYYY-MM-DD
        url = release["html_url"]
        body = (release.get("body") or "").strip()
        prerelease_label = " *(pre-release)*" if release.get("prerelease") else ""

        lines.append(f"## [{name}]({url}){prerelease_label}\n")
        lines.append(f"*Released: {date} — [View on GitHub]({url})*\n")
        if body:
            lines.append(body + "\n")
        lines.append("---\n")

    print(f"Docs saved to: {RELEASES_PAGE}")
    RELEASES_PAGE.write_text("\n".join(lines))


def generate_cli_docs() -> None:
    """Build CLI command docs using typer's built-in doc generation tool: https://typer.tiangolo.com/tutorial/typer-command/#generate-docs"""
    result = subprocess.run(
        [
            "typer",
            str(CLI_ENTRY_POINT),
            "utils",
            "docs",
            "--name",
            "divbase-cli",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    # Keep only the top level command output (e.g. divbase-cli --help)
    overview_content = result.stdout.split("##")[0].strip()

    CLI_SAVE_DIR.mkdir(parents=True, exist_ok=True)
    output_file = CLI_SAVE_DIR / "divbase-cli.md"
    output_file.write_text(overview_content)

    for cmd_name, cmd_path in SUB_COMMANDS.items():
        output_file = CLI_SAVE_DIR / f"{cmd_name}.md"
        subprocess.run(
            [
                "typer",
                str(cmd_path),
                "utils",
                "docs",
                "--name",
                f"divbase-cli {cmd_name}",
                "--output",
                str(output_file),
            ],
            check=True,
        )


if __name__ == "__main__":
    generate_releases_page()
    generate_cli_docs()
    nav_sections = parse_all_nav_sections()
    generate_llms_full(nav_sections)
    generate_llms_users(nav_sections)
    generate_llms_txt(nav_sections)
