"""
Tests for database migrations autogenerated via pytest-alembic plugin.

By importing these here we can have them run by default without needing to pass a flag.
https://pytest-alembic.readthedocs.io/en/latest/running.html#alternative-to-test-alembic
"""

from pytest_alembic.tests import (
    test_model_definitions_match_ddl,  # noqa: F401
    test_single_head_revision,  # noqa: F401
    test_up_down_consistency,  # noqa: F401
    test_upgrade,  # noqa: F401
)
