sequenceDiagram
    title Task status list: sequence diagram
    participant User
    participant CLI
    participant API
    participant DB as DB (postgreSQL)
    participant Flower
    participant Redis as Redis (Celery Results Backend)

    User->>CLI: Run "divbase-cli task-history list"
    CLI->>API: HTTP GET /api/v1/task-history/list (optional params: project, limit)
    API->>DB: Query allowed task IDs for user/project
    DB-->>API: Return allowed task IDs

    alt No allowed task IDs for user/project
        API-->>CLI: Return empty result
        CLI->>User: Display empty result
    else Allowed task IDs found
        API->>Flower: HTTP GET /api/tasks?limit={api_limit}
        Flower->>Redis: Fetch task data
        Redis-->>Flower: Return task data
        Flower-->>API: Return all tasks
        API->>API: Filter tasks by allowed IDs and project
        API-->>CLI: Return filtered TaskHistoryResults
        CLI->>User: Display results in terminal
    end


%% Version without early-exit ALT sequences
    %% User->>CLI: Run "divbase-cli query task-status TODO"
    %% CLI->>API: HTTP GET /api/v1/task-history/list (optional params: project, limit)
    %% API->>DB: Query allowed task IDs for user/project
    %% DB-->>API: Return allowed task IDs
    %% API->>Flower: HTTP GET /api/tasks?limit={api_limit}"
    %% Flower->>Redis: Fetch task data
    %% Redis-->>Flower: Return task data
    %% Flower-->>API: Return all tasks
    %% API->>API: Filter tasks by allowed IDs and project
    %% API-->>CLI: Return filtered TaskHistoryResults
    %% CLI->>User: Display results in terminal
