name: Run pre-commit checks 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pre-commit==4.2.0

    - name: Run pre-commit
      run: pre-commit run --all-files