name: Build and deploy the divbase documentation website
on:
  # NOTE: A new release will auto publish a new version of the docs, see release.yaml.
  workflow_dispatch:

jobs:
  docs:
    name: Build and publish DivBase documentation site to GitHub pages
    if: github.repository == 'ScilifelabDataCentre/divbase'
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/build-docs.yaml
