name: Run pytest when new images built and published to GHCR
on:
  workflow_run:
    workflows: ["Build and Push images to GitHub Container Registry"]
    types:
      - completed

jobs:
  run-pytest-on-newly-built-images:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install bcftools # some test set up data calling bcftool directly
        run: | 
          sudo apt-get update  
          sudo apt-get install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libperl-dev libgsl0-dev
          git clone --recurse-submodules https://github.com/samtools/htslib.git
          git clone https://github.com/samtools/bcftools.git
          cd bcftools
          make

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.15"
          enable-cache: true

      - name: Install the project
        run: | 
          uv sync --locked --dev
          uv run playwright install chromium

      - name: Pull new images built in the previous workflow run
        env:
          TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          docker pull ghcr.io/scilifelabdatacentre/divbase-fastapi:$TAG
          docker pull ghcr.io/scilifelabdatacentre/divbase-worker:$TAG

      - name: Run pytest including slow tests
        env: 
          GITHUB_ACTIONS_RUNNER: "true"
          DIVBASE_FASTAPI_IMAGE: ghcr.io/scilifelabdatacentre/divbase-fastapi:${{ github.event.workflow_run.head_sha }}
          DIVBASE_WORKER_IMAGE: ghcr.io/scilifelabdatacentre/divbase-worker:${{ github.event.workflow_run.head_sha }}
        run: FORCE_TERMINAL=1 COLUMNS=1000 uv run pytest --run-slow