"""
Standalone script for cleaning up "expired" soft-deleted S3 objects (aka hard delete).

Run as a K8s CronJob in a separate namespace to rest of application.
This cron job uses a different S3 service account that has s3:DeleteObjectVersion permissions.

For versioned buckets (which DivBase uses):
- deleting an object without specifying a version id just adds a deletion marker.
- If you specify the version id, it hard deletes that specific version of the object.

### Deletion approach:
1. Results files generated by vcf queries are hard deleted after a certain retention period (e.g. 30 days).
    - No consideration about soft vs hard delete status for these files.
2. All other files that have been soft-deleted for more than a certain retention period (e.g. 30 days) are hard deleted,
    - This rule has 1 exception, if a version of a file is recorded in a user defined project version, then it is not hard deleted.
    - Project versions let user define specific versions of files they want to protect from hard deletion.

    If no file versions are protected by a project version, then all versions (and delete markers) of the file are hard deleted.

    If 1 or more specific versions of a file is protected by a project version, then:
       - all other versions of the file (and all delete markers) will be deleted.
       - The protected versions are NOT deleted.
       - A new delete marker (soft delete) is placed on top of the protected file to prevent a protected version from now becoming the latest version,
            If we do not do this it would show up in e.g. divbase-cli files ls, be downloadable and be usable in query jobs.
            This would not be expected since the file was soft deleted and the user expected it to be gone.
"""

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

import stamina
from pydantic import SecretStr
from sqlalchemy import create_engine, select
from sqlalchemy.orm import sessionmaker

from divbase_api.models.project_versions import ProjectVersionDB
from divbase_api.models.projects import ProjectDB
from divbase_api.services.s3_client import S3_BATCH_SIZE, S3FileManager
from divbase_lib.divbase_constants import QUERY_RESULTS_FILE_PREFIX

logger = logging.getLogger(__name__)


class HardDeletePartialFailureError(Exception):
    """Raised when one or more objects could not be hard-deleted after all retry attempts."""

    def __init__(self, errors: list[dict]):
        self.errors = errors
        super().__init__(errors)


DEFAULT_RESULTS_FILES_RETENTION_DAYS = 30
DEFAULT_SOFT_DELETED_FILES_RETENTION_DAYS = 30


@dataclass
class CronJobConfig:
    """Config for the cron job"""

    db_url: SecretStr = field(default_factory=lambda: SecretStr(os.environ["SYNC_DATABASE_URL"]))
    endpoint_url: str = field(default_factory=lambda: os.environ["S3_ENDPOINT_URL"])
    access_key: SecretStr = field(default_factory=lambda: SecretStr(os.environ["S3_CRON_SERVICE_ACCOUNT_ACCESS_KEY"]))
    secret_key: SecretStr = field(default_factory=lambda: SecretStr(os.environ["S3_CRON_SERVICE_ACCOUNT_SECRET_KEY"]))
    task_files_retention_days: int = field(default_factory=lambda: int(os.getenv("TASK_FILES_RETENTION_DAYS", "30")))
    soft_deleted_files_retention_days: int = field(
        default_factory=lambda: int(os.getenv("SOFT_DELETED_FILES_RETENTION_DAYS", "30"))
    )


@dataclass
class ProjectHardDeleteContext:
    project_name: str
    bucket_name: str
    # key is filename, values is a set of version IDs that must not be hard-deleted
    # as they are in a user defined project version.
    protected_versions_map: dict[str, set[str]] = field(default_factory=dict)


def load_project_contexts(db_url: SecretStr) -> list[ProjectHardDeleteContext]:
    """
    Query the DB to get all project versions for all projects.
    Returns a dataclass containing each project's protected files, so we know what not to delete in s3.

    This tells us what specific versions of every file should not be hard deleted essentially.
    """
    sync_engine = create_engine(db_url.get_secret_value(), echo=False, pool_pre_ping=True)
    SyncSessionLocal = sessionmaker(bind=sync_engine)

    contexts = []
    with SyncSessionLocal() as db:
        projects = db.execute(select(ProjectDB)).scalars().all()
        for project in projects:
            protected_versions_map: dict[str, set[str]] = {}

            project_versions = (
                db.execute(select(ProjectVersionDB).where(ProjectVersionDB.project_id == project.id)).scalars().all()
            )

            for version in project_versions:
                if not version.files:
                    continue
                for filename, version_details in version.files.items():
                    version_id = version_details["version_id"]
                    if filename not in protected_versions_map:
                        protected_versions_map[filename] = set()
                    protected_versions_map[filename].add(version_id)

            contexts.append(
                ProjectHardDeleteContext(
                    project_name=project.name,
                    bucket_name=project.bucket_name,
                    protected_versions_map=protected_versions_map,
                )
            )
    return contexts


def hard_delete_objects(
    s3_file_manager: S3FileManager, bucket_name: str, objects_to_delete: list[dict[str, str]]
) -> None:
    """
    Hard delete specified objects in batches from a bucket.
    Can be used to hard delete both files and delete markers.

    objects_to_delete is a list of dicts with keys "Key" and "VersionId".

    We use stamina to retry any failed deletions, S3 reports back failed deletion in response, not via raising errors.
    If after all retries there are still failures, an error will be raised.
    """
    pending = list(objects_to_delete)
    for attempt in stamina.retry_context(on=HardDeletePartialFailureError, attempts=4):
        with attempt:
            failures = []
            for i in range(0, len(pending), S3_BATCH_SIZE):
                batch = pending[i : i + S3_BATCH_SIZE]
                response = s3_file_manager.s3_client.delete_objects(Bucket=bucket_name, Delete={"Objects": batch})
                failures.extend({"Key": e["Key"], "VersionId": e["VersionId"]} for e in response.get("Errors", []))
            if failures:
                pending = failures
                logger.warning(
                    f"Attempt: {attempt} to hard delete objects had {len(failures)} failures, retrying. Failures were: {failures}"
                )
                raise HardDeletePartialFailureError(failures)


def delete_expired_results_files(
    s3_file_manager: S3FileManager, buckets: list[str], results_files_retention_days: int
) -> tuple[int, int, bool]:
    """
    Results files older than cutoff date are considered expired and are hard deleted.

    We also cover any delete markers that may have been placed on the results files, to ensure they are also fully purged.

    Returns a tuple of (number of results files deleted, number of delete markers deleted, had_errors).
    """
    cutoff_date = datetime.now(timezone.utc) - timedelta(days=results_files_retention_days)
    total_results_files_deleted = 0
    total_delete_markers_deleted = 0
    had_errors = False

    for bucket_name in buckets:
        results_files_to_delete, delete_markers_to_delete = [], []
        paginator = s3_file_manager.s3_client.get_paginator("list_object_versions")

        args = {"Bucket": bucket_name, "Prefix": QUERY_RESULTS_FILE_PREFIX}
        for page in paginator.paginate(**args):
            for obj in page.get("Versions", []):
                if obj["LastModified"] < cutoff_date:
                    results_files_to_delete.append({"Key": obj["Key"], "VersionId": obj["VersionId"]})

            for marker in page.get("DeleteMarkers", []):
                if marker["LastModified"] < cutoff_date:
                    delete_markers_to_delete.append({"Key": marker["Key"], "VersionId": marker["VersionId"]})

        if not results_files_to_delete and not delete_markers_to_delete:
            continue

        objects_to_delete = results_files_to_delete + delete_markers_to_delete
        try:
            hard_delete_objects(
                s3_file_manager=s3_file_manager,
                bucket_name=bucket_name,
                objects_to_delete=objects_to_delete,
            )
        except HardDeletePartialFailureError:
            logger.error(f"Failed to hard delete all results files in bucket {bucket_name} after all retries.")
            had_errors = True
            continue

        total_results_files_deleted += len(results_files_to_delete)
        total_delete_markers_deleted += len(delete_markers_to_delete)

    return total_results_files_deleted, total_delete_markers_deleted, had_errors


def delete_expired_non_results_files(
    s3_file_manager: S3FileManager,
    project_contexts: list[ProjectHardDeleteContext],
    soft_deleted_files_retention_days: int,
) -> tuple[int, int, bool]:
    """
    Soft-deleted files that are not results files and that have been soft-deleted for longer than the retention period are hard deleted, with exceptions for protected versions.

    Returns a tuple of (number of non-results files deleted, number of delete markers deleted, had_errors).
    """
    cutoff_date = datetime.now(timezone.utc) - timedelta(days=soft_deleted_files_retention_days)

    numb_deleted_non_results_files = 0
    numb_deleted_non_results_files_deletion_markers = 0
    had_errors = False
    for ctx in project_contexts:
        candidate_objects_to_purge = s3_file_manager.get_expired_soft_deleted_objects(
            bucket_name=ctx.bucket_name,
            cutoff_date=cutoff_date,
            prefix_exclude=QUERY_RESULTS_FILE_PREFIX,
        )
        logger.debug(
            f"Project {ctx.project_name} has {len(candidate_objects_to_purge)} candidate non-results files to purge."
        )

        objects_to_re_soft_delete = []
        for object_name in candidate_objects_to_purge:
            protected_ids = ctx.protected_versions_map.get(object_name, set())

            versions_resp = s3_file_manager.s3_client.list_object_versions(Bucket=ctx.bucket_name, Prefix=object_name)
            # list_object_versions uses a prefix for matching so we need == for exact key/file
            exact_versions = [v for v in versions_resp.get("Versions", []) if v["Key"] == object_name]
            exact_delete_markers = [m for m in versions_resp.get("DeleteMarkers", []) if m["Key"] == object_name]

            versions_to_delete = []
            for version in exact_versions:
                if version["VersionId"] not in protected_ids:
                    versions_to_delete.append({"Key": object_name, "VersionId": version["VersionId"]})

            markers_to_delete = []
            for marker in exact_delete_markers:
                markers_to_delete.append({"Key": object_name, "VersionId": marker["VersionId"]})

            # first hard delete the non-protected file versions.
            try:
                if versions_to_delete:
                    hard_delete_objects(
                        s3_file_manager=s3_file_manager,
                        bucket_name=ctx.bucket_name,
                        objects_to_delete=versions_to_delete,
                    )
            except HardDeletePartialFailureError:
                logger.error(
                    f"Failed to hard delete versions for {object_name} after all retries, skipping deleting this files delete markers."
                )
                # If this fails, we leave delete markers intact
                # so file definitely remains soft-deleted and we can retry again another time
                had_errors = True
                continue

            # now we hard delete the delete markers.
            try:
                if markers_to_delete:
                    hard_delete_objects(
                        s3_file_manager=s3_file_manager,
                        bucket_name=ctx.bucket_name,
                        objects_to_delete=markers_to_delete,
                    )
            except HardDeletePartialFailureError:
                logger.error(
                    f"Failed to hard delete delete markers for {object_name} after all retries. "
                    "Versions were deleted but original delete markers remain — file stays soft-deleted."
                )
                numb_deleted_non_results_files += len(versions_to_delete)
                had_errors = True
                continue

            numb_deleted_non_results_files += len(versions_to_delete)
            numb_deleted_non_results_files_deletion_markers += len(markers_to_delete)

            # If any version of this file is protected, the protected version would now become the
            # latest visible version (since we deleted all non-protected versions and all markers).
            # Re-add a delete marker so it doesn't appear in listings or be usable in query jobs.
            if any(v["VersionId"] in protected_ids for v in exact_versions):
                objects_to_re_soft_delete.append(object_name)

        if objects_to_re_soft_delete:
            s3_file_manager.soft_delete_objects(
                objects=objects_to_re_soft_delete,
                bucket_name=ctx.bucket_name,
            )

    return numb_deleted_non_results_files, numb_deleted_non_results_files_deletion_markers, had_errors


def main() -> None:
    """See docstring at top of file for description"""
    logging.basicConfig(level=logging.INFO)

    job_config = CronJobConfig()
    s3_file_manager = S3FileManager(
        url=job_config.endpoint_url,
        access_key=job_config.access_key.get_secret_value(),
        secret_key=job_config.secret_key.get_secret_value(),
    )

    logger.info(
        f"Starting hard_delete_expired_files cron job with configuration settings: \n"
        f"endpoint_url={job_config.endpoint_url} \n"
        f"soft_deleted_files_retention_days={job_config.soft_deleted_files_retention_days} \n"
        f"task_files_retention_days={job_config.task_files_retention_days}",
    )

    project_contexts = load_project_contexts(db_url=job_config.db_url)
    logger.info(f"Loaded project contexts for {len(project_contexts)} projects.")
    all_buckets = list(set(ctx.bucket_name for ctx in project_contexts))
    logger.info(f"buckets are {all_buckets}")

    numb_deleted_results_files, numb_deleted_results_files_deletion_markers, results_had_errors = (
        delete_expired_results_files(
            s3_file_manager=s3_file_manager,
            buckets=all_buckets,
            results_files_retention_days=job_config.task_files_retention_days,
        )
    )

    numb_deleted_non_results_files, numb_deleted_non_results_files_deletion_markers, non_results_had_errors = (
        delete_expired_non_results_files(
            s3_file_manager=s3_file_manager,
            project_contexts=project_contexts,
            soft_deleted_files_retention_days=job_config.soft_deleted_files_retention_days,
        )
    )

    logger.info(
        "hard_delete_expired_files cron job completed:\n "
        f"Total number of hard deleted results files: {numb_deleted_results_files}\n"
        f"Total number of hard deleted results file deletion markers: {numb_deleted_results_files_deletion_markers}\n"
        f"Total number of other objects hard deleted: {numb_deleted_non_results_files}\n"
        f"Total number of delete markers hard deleted: {numb_deleted_non_results_files_deletion_markers}"
    )

    # as this is run as a cron job, lets make it easier to monitor for issues.
    if results_had_errors or non_results_had_errors:
        raise RuntimeError("hard_delete_expired_files cron job completed with errors, see logs above for details.")


if __name__ == "__main__":
    main()
